use super::super::*;
use wasm_bindgen::prelude::wasm_bindgen;

#[wasm_bindgen]
impl IdleGame {
    #[wasm_bindgen(constructor)]
    pub fn new() -> IdleGame {
        let now = Date::now();

        let achievements = vec![
            // Click achievements
            Achievement {
                id: "click_novice_10".to_string(),
                name: "点击新手".to_string(),
                description: "点击 10 次".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 10.0,
                category: "clicks".to_string(),
            },
            Achievement {
                id: "click_master_100".to_string(),
                name: "点击大师".to_string(),
                description: "点击 100 次".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 100.0,
                category: "clicks".to_string(),
            },
            Achievement {
                id: "click_legend_1000".to_string(),
                name: "点击传奇".to_string(),
                description: "点击 1000 次".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 1000.0,
                category: "clicks".to_string(),
            },
            // Resource achievements
            Achievement {
                id: "first_coins_100".to_string(),
                name: "第一桶金".to_string(),
                description: "获得 100 金币".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 100.0,
                category: "resources".to_string(),
            },
            Achievement {
                id: "wood_collector_1000".to_string(),
                name: "木材收集者".to_string(),
                description: "获得 1000 木头".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 1000.0,
                category: "resources".to_string(),
            },
            Achievement {
                id: "stone_hoarder_5000".to_string(),
                name: "石头囤积者".to_string(),
                description: "获得 5000 石头".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 5000.0,
                category: "resources".to_string(),
            },
            // Building achievements
            Achievement {
                id: "first_building".to_string(),
                name: "第一座建筑".to_string(),
                description: "购买第一座建筑".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 1.0,
                category: "buildings".to_string(),
            },
            Achievement {
                id: "building_enthusiast_10".to_string(),
                name: "建筑爱好者".to_string(),
                description: "购买 10 座建筑".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 10.0,
                category: "buildings".to_string(),
            },
            Achievement {
                id: "building_tycoon_50".to_string(),
                name: "建筑大亨".to_string(),
                description: "购买 50 座建筑".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 50.0,
                category: "buildings".to_string(),
            },
            // Crafting achievements
            Achievement {
                id: "first_craft".to_string(),
                name: "第一次加工".to_string(),
                description: "通过工厂产出第一个加工资源".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 1.0,
                category: "crafting".to_string(),
            },
            Achievement {
                id: "craft_master_100".to_string(),
                name: "工业大师".to_string(),
                description: "通过工厂累计产出 100 个加工资源".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 100.0,
                category: "crafting".to_string(),
            },
            // Unlock achievements
            Achievement {
                id: "first_unlock".to_string(),
                name: "首次解锁".to_string(),
                description: "解锁第一个成就".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 1.0,
                category: "unlocks".to_string(),
            },
            Achievement {
                id: "progress_master_5".to_string(),
                name: "进度大师".to_string(),
                description: "解锁 5 个成就".to_string(),
                unlocked: false,
                unlock_timestamp: None,
                progress: 0.0,
                requirement: 5.0,
                category: "unlocks".to_string(),
            },
        ];

        IdleGame {
            state: Rc::new(RefCell::new(GameState {
                resources: {
                    let mut resources = HashMap::new();
                    resources.insert(ResourceType::Gold, 0.0);
                    resources.insert(ResourceType::Wood, 0.0);
                    resources.insert(ResourceType::Stone, 0.0);
                    resources
                },
                coins_per_click: 1.0,
                coins_per_second: 0.0,
                wood_per_second: 0.0,
                stone_per_second: 0.0,
                total_clicks: 0,
                last_update_time: now,
                version: crate::state::game_state::SAVE_VERSION.to_string(),
                prestige_points: 0.0,
                prestige_multiplier: 1.0,
                ..GameState::default()
            })),
            statistics: Rc::new(RefCell::new(Statistics {
                total_clicks: 0,
                total_coins_earned: 0.0,
                total_wood_earned: 0.0,
                total_stone_earned: 0.0,
                total_resources_crafted: 0,
                achievements_unlocked_count: 0,
                play_time_seconds: 0.0,
                buildings_purchased: 0,
                upgrades_purchased: 0,
            })),
            achievements: achievements,
            buildings: vec![
                // 10 primary resource buildings
                Building {
                    name: "金币矿山".to_string(),
                    cost: 15.0,
                    production_rate: 1.0,
                    output_resource: ResourceType::Gold,
                    count: 0,
                },
                Building {
                    name: "伐木场".to_string(),
                    cost: 20.0,
                    production_rate: 1.0,
                    output_resource: ResourceType::Wood,
                    count: 0,
                },
                Building {
                    name: "采石场".to_string(),
                    cost: 25.0,
                    production_rate: 0.5,
                    output_resource: ResourceType::Stone,
                    count: 0,
                },
                Building {
                    name: "铁矿场".to_string(),
                    cost: 50.0,
                    production_rate: 0.5,
                    output_resource: ResourceType::IronOre,
                    count: 0,
                },
                Building {
                    name: "铜矿场".to_string(),
                    cost: 40.0,
                    production_rate: 0.6,
                    output_resource: ResourceType::CopperOre,
                    count: 0,
                },
                Building {
                    name: "铝矿场".to_string(),
                    cost: 60.0,
                    production_rate: 0.4,
                    output_resource: ResourceType::AluminumOre,
                    count: 0,
                },
                Building {
                    name: "煤矿场".to_string(),
                    cost: 70.0,
                    production_rate: 0.5,
                    output_resource: ResourceType::Coal,
                    count: 0,
                },
                Building {
                    name: "石油井".to_string(),
                    cost: 100.0,
                    production_rate: 0.3,
                    output_resource: ResourceType::Oil,
                    count: 0,
                },
                Building {
                    name: "水晶矿".to_string(),
                    cost: 150.0,
                    production_rate: 0.2,
                    output_resource: ResourceType::Crystal,
                    count: 0,
                },
                Building {
                    name: "农场".to_string(),
                    cost: 30.0,
                    production_rate: 2.0,
                    output_resource: ResourceType::Food,
                    count: 0,
                },
                Building {
                    name: "腐食育蛆槽".to_string(),
                    cost: 160.0,
                    production_rate: 0.5,
                    output_resource: ResourceType::Maggot,
                    count: 0,
                },
                Building {
                    name: "蛆虫工厂".to_string(),
                    cost: 200.0,
                    production_rate: 1.0,
                    output_resource: ResourceType::Maggot,
                    count: 0,
                },
                Building {
                    name: "腐肉育池".to_string(),
                    cost: 420.0,
                    production_rate: 3.0,
                    output_resource: ResourceType::Maggot,
                    count: 0,
                },
                Building {
                    name: "共生培育舱".to_string(),
                    cost: 1800.0,
                    production_rate: 8.0,
                    output_resource: ResourceType::Food,
                    count: 0,
                },
                Building {
                    name: "神经尖塔".to_string(),
                    cost: 9000.0,
                    production_rate: 0.3,
                    output_resource: ResourceType::DarkMatter,
                    count: 0,
                },
                Building {
                    name: "深空孵化港".to_string(),
                    cost: 22000.0,
                    production_rate: 0.08,
                    output_resource: ResourceType::Spaceship,
                    count: 0,
                },
                factory_building("铁锭冶炼厂", 220.0, 0.1, ResourceType::IronIngot),
                factory_building("铜锭冶炼厂", 240.0, 0.1, ResourceType::CopperIngot),
                factory_building("化学品厂", 420.0, 0.08, ResourceType::Chemicals),
                factory_building("钢铁厂", 520.0, 0.06, ResourceType::SteelPlate),
                factory_building("玻璃厂", 460.0, 0.08, ResourceType::Glass),
                factory_building("塑料厂", 540.0, 0.08, ResourceType::Plastic),
                factory_building("电路板厂", 760.0, 0.065, ResourceType::CircuitBoard),
                factory_building("马达厂", 1200.0, 0.04, ResourceType::Motor),
                factory_building("传感器厂", 1250.0, 0.04, ResourceType::Sensor),
                factory_building("齿轮厂", 750.0, 0.06, ResourceType::Gear),
                factory_building("电池厂", 1200.0, 0.05, ResourceType::Battery),
                factory_building("发电机厂", 1800.0, 0.04, ResourceType::Generator),
                factory_building("芯片制造厂", 2600.0, 0.04, ResourceType::Microchip),
                factory_building("量子计算中心", 7000.0, 0.012, ResourceType::QuantumComputer),
                factory_building("机器人工厂", 5200.0, 0.02, ResourceType::Robot),
                factory_building("纳米机器人工厂", 9000.0, 0.015, ResourceType::Nanobot),
                factory_building("反物质反应堆", 25000.0, 0.005, ResourceType::Antimatter),
                factory_building("时间水晶合成器", 28000.0, 0.005, ResourceType::TimeCrystal),
            ],
            housing_buildings: default_housing_catalog(),
            workers: vec![],
            population_queue: PopulationQueue::new(),
            last_food_consumption_time: now,
            last_worker_spawn_time: now,
            unlocked_features: vec![
                UnlockedFeature {
                    id: "workers_tab".to_string(),
                    name: "工人面板".to_string(),
                    feature_type: "area".to_string(),
                    unlocked: false,
                    unlock_timestamp: None,
                    requirement_type: "total_clicks".to_string(),
                    requirement_value: 50.0,
                },
                UnlockedFeature {
                    id: "advanced_buildings".to_string(),
                    name: "高级建筑".to_string(),
                    feature_type: "building".to_string(),
                    unlocked: false,
                    unlock_timestamp: None,
                    requirement_type: "buildings_owned".to_string(),
                    requirement_value: 20.0,
                },
                UnlockedFeature {
                    id: "prestige_system".to_string(),
                    name: "转生系统".to_string(),
                    feature_type: "mechanic".to_string(),
                    unlocked: false,
                    unlock_timestamp: None,
                    requirement_type: "total_coins".to_string(),
                    requirement_value: 10000.0,
                },
                UnlockedFeature {
                    id: "statistics_panel".to_string(),
                    name: "统计面板".to_string(),
                    feature_type: "area".to_string(),
                    unlocked: false,
                    unlock_timestamp: None,
                    requirement_type: "total_clicks".to_string(),
                    requirement_value: 10.0,
                },
                UnlockedFeature {
                    id: "achievements_panel".to_string(),
                    name: "成就面板".to_string(),
                    feature_type: "area".to_string(),
                    unlocked: false,
                    unlock_timestamp: None,
                    requirement_type: "total_clicks".to_string(),
                    requirement_value: 25.0,
                },
            ],
            technology_tree: TechnologyTree::new(),
        }
    }
}
