use crate::entities::Trait;

pub fn trait_voice_pack_en(
    trait_value: Trait,
) -> (
    &'static [&'static str],
    &'static [&'static str],
    &'static [&'static str],
) {
    match trait_value {
        Trait::Diligent
        | Trait::Hardworking
        | Trait::Efficient
        | Trait::Persevering
        | Trait::Careful => (
            &[
                "Hold the station first",
                "This is exactly when people cannot scatter",
                "If the process still moves, there is still a chance",
                "Get through this cycle first",
                "Do not waste today",
                "Lock the critical stations down first",
                "This is where letting go becomes expensive",
                "The crew cannot come apart on a turn like this",
                "Keep today's losses contained first",
                "Whatever happens, the line still has to be caught",
            ],
            &[
                "At least the crews still know their jobs",
                "The real danger is losing the rhythm",
                "I would rather take another shift than watch the system stop",
                "What we need now is steadier planning",
                "The station is more honest than the slogan",
                "If the process remains intact, recovery is still possible",
                "People need actionable dispatch, not ceremonial language",
                "Machines and crews both punish hesitation",
                "Give the floor a next step and panic does not get the first move",
                "Every spare minute now should go into keeping the line alive",
            ],
            &[
                "Do not let go.",
                "Hold this round together.",
                "Fix what can still be fixed.",
                "The numbers can lie, the station usually does not.",
                "Stability matters most right now.",
                "Do not let the line drop.",
                "If it is time to hold, then hold.",
                "Catch the work first.",
                "If we stay steady, there is still a tomorrow.",
                "Close the breach first.",
                "Do not let the process lose its breath.",
                "Hold this shift first.",
                "Steady beats elegant right now.",
                "Keep the line alive.",
                "This is no time to shake loose.",
            ],
        ),
        Trait::Lazy
        | Trait::Slow
        | Trait::SlowLearner
        | Trait::Clumsy
        | Trait::Careless
        | Trait::Forgetful => (
            &[
                "Sounds like overtime again",
                "They always call it temporary",
                "I mostly want to know if tonight gets harder",
                "News arrives faster than food",
                "Please do not rewrite the process again",
                "Every incident somehow becomes our overtime",
                "I knew this was never going away quietly",
                "Even catching one breath feels expensive right now",
                "The ugliest jobs always land on whoever is on shift",
                "So this is another emergency adjustment, huh",
            ],
            &[
                "Every report says controllable and then another stack of forms shows up",
                "If it did not land on my shift, I might ignore it",
                "Do not dump every mess on the floor",
                "I really hope nobody makes this even more complicated",
                "This already sounds exhausting",
                "One sentence upstairs means three extra loops downstairs",
                "I just do not want a simple problem turned into a permanent burden",
                "Maybe guarantee food and sleep before adding another slogan",
                "It always ends with crews absorbing the consequence themselves",
                "If the process changes one more time, someone is definitely missing the handoff",
            ],
            &[
                "I hope this ends quickly.",
                "Do not drag it out.",
                "Please do not make it permanent.",
                "I am not losing a whole night to this.",
                "Keep it simple.",
                "Let me survive this shift first.",
                "Do not pile more on today.",
                "Do not let inconvenience become policy.",
                "I would like to leave on time once.",
                "Please stop pushing downward.",
                "Do not hand me another layer of blame.",
                "Can today just stop here.",
                "Please no new tricks tonight.",
                "Let me breathe first.",
                "This does not need to escalate.",
            ],
        ),
        Trait::Intelligent | Trait::FastLearner | Trait::Genius | Trait::Creative => (
            &[
                "The causal chain is actually visible",
                "From a system perspective",
                "I suspect this is only one face of a larger pattern",
                "If you spread the variables out",
                "There has to be a repeatable structure underneath this",
                "I would rather treat this as an analyzable sample",
                "Do not call it an accident too quickly",
                "This node is appearing with suspicious regularity",
                "Across the chain, this is not as sudden as it looks",
                "Put the before-and-after readings side by side",
            ],
            &[
                "The phenomenon matters more than the official line",
                "They are describing outcomes rather than mechanisms",
                "The real question is why it surfaced now",
                "Once the sample gets larger, this stops looking mystical",
                "I care more about how it rewrites downstream logic",
                "What matters is why the system allowed it to happen",
                "Each anomaly is exposing a weak segment of the main loop",
                "Watching the surface wave alone misses the core factor",
                "This is not a one-off, it is a threshold being touched",
                "If the model is right, the next swing comes sooner",
            ],
            &[
                "This is structure, not noise.",
                "I want the raw log.",
                "Someone will model this sooner or later.",
                "There is a key hidden inside this.",
                "What we lack is honest data.",
                "Map the causal chain first.",
                "Do not let mood outrun the sample.",
                "Structure matters more than rhetoric.",
                "The pattern will expose itself again.",
                "The key variables are already visible.",
                "Do not waste this sample.",
                "The pattern is already speaking.",
                "This line of data is expensive.",
                "Plot first, argue later.",
                "The answer is in the sequence.",
            ],
        ),
        Trait::Social | Trait::Charismatic | Trait::Optimistic => (
            &[
                "Everybody is talking about this today",
                "The moment the bulletin landed, the room reacted",
                "Every crew heard the rumor",
                "You could read it on people's faces",
                "The mood shifted immediately",
                "Even the quiet ones started trading updates",
                "The hallway changed topics in minutes",
                "The way people looked at each other changed with the bulletin",
                "The rumor outran the speaker system",
                "Even the canteen is talking about it now",
            ],
            &[
                "Panic travels faster than policy, but hope does too",
                "If someone explains it plainly, the team will hold",
                "I would rather hear fear out loud than watch it ferment in silence",
                "People need language they can actually trust",
                "As long as the rhythm does not fully break, the floor will not either",
                "People fear silence more than bad news",
                "If someone owns the explanation, the mood stops falling quite so fast",
                "Rumor grows on its own, so response has to move faster",
                "We need one shared version of the same event",
                "Crews do not scatter because of truth, they scatter because no one speaks clearly",
            ],
            &[
                "This is not the worst point yet.",
                "Somebody always catches the fall.",
                "We do not need to scare each other into collapse.",
                "At least we are still on one line.",
                "If change is coming, we face it together.",
                "Do not bury hope before the facts do.",
                "If we can explain it, we still have room.",
                "Do not let morale scatter first.",
                "People need to know they are not alone in the room.",
                "Even bad news can be carried steadily.",
                "Do not let rumor win.",
                "Explain it before fear does.",
                "If people remain, the line remains.",
                "Gather the mood first.",
                "Do not let the crew break before the system does.",
            ],
        ),
        Trait::Loner | Trait::Shy => (
            &[
                "I do not usually take part in these discussions",
                "If you really need a quote",
                "I prefer to write things down first",
                "I do not want to conclude too early",
                "Take this as a private observation",
                "I would rather watch two more cycles first",
                "Please do not put my name in large type",
                "I usually speak only when asked directly",
                "I am not sure this belongs in the open yet",
                "If you record it, record the fact and not the noise",
            ],
            &[
                "When everyone gets loud, the key details disappear first",
                "Some changes are easier to see in silence",
                "Not speaking does not mean not noticing",
                "I do not think anyone fully understands it yet",
                "Watching one more cycle would be safer",
                "Many things are not absent, only drowned out",
                "I trust repeated details more than first explanations",
                "Truth rarely sits in the loudest corner",
                "Give it one more shift and half the current talking points will collapse",
                "A careful record is worth more than a fast position",
            ],
            &[
                "Do not rush the conclusion.",
                "There is too much noise.",
                "Truth usually hides in the quiet parts.",
                "It is too early for certainty.",
                "Clarity is what is missing right now.",
                "Give it more quiet.",
                "Do not pick a side too early.",
                "Let me watch one more round.",
                "Silence is carrying more information.",
                "It is too soon to lock the story down.",
                "Do not let heat replace judgment.",
                "Keep the details first.",
                "Misreading is the real risk right now.",
                "One more cycle will tell more.",
                "Quiet is where the truth is still audible.",
            ],
        ),
        Trait::NightOwl | Trait::EarlyBird => (
            &[
                "This kind of swing always speaks through timing",
                "Day crews and night crews are seeing different worlds",
                "Shift edges reveal the problem fastest",
                "I noticed the rhythm change before most people did",
                "Time windows are part of the issue itself",
                "These swings always arrive at the worst possible hour",
                "Morning crews and night crews are not reading the same picture",
                "The timing gap exposes more than the headline does",
                "I track when it arrives, not just what it is called",
                "Time tells the truth before policy does",
            ],
            &[
                "Any conclusion built on one shift alone will be biased",
                "The turning point always arrives when people are either tired or loose",
                "Response plans should be organized around time windows",
                "Once rhythm breaks, time is the first casualty",
                "The clock is often more honest than the report",
                "One line speaks differently depending on which shift is watching it",
                "To catch the pattern, first catch the hour it prefers",
                "A lot of failures are assembled inside handoff seams",
                "Time distribution is evidence, not scenery",
                "If scheduling is wrong, even perfect messaging starts leaking",
            ],
            &[
                "Look at another shift and it gets clearer.",
                "This has a visible time texture.",
                "Watch one more time window.",
                "Signals do not arrive at random.",
                "It has its own sequence.",
                "Do not ignore the handoff line.",
                "The clock reads truer than the faces do.",
                "It always shows up in a favored slot.",
                "Track one more sequence.",
                "Rhythm speaks for itself.",
                "Watch the clock, not just the faces.",
                "It enters in fixed order.",
                "Wait for the next window.",
                "Handoffs leak truth first.",
                "Start with the timeline.",
            ],
        ),
    }
}
