use crate::entities::technology::TechnologyId;
use crate::entities::Trait;
use crate::state::{EventCategory, EventImpact, GameStage};

#[derive(Clone, Copy)]
pub(super) enum TriggerFamily {
    Baseline,
    FoodStress,
    FoodGlutStall,
    DarkSignal,
    HybridFlux,
    CollectiveSignal,
}

#[derive(Clone, Copy)]
pub(super) enum EventEffect {
    None,
    AddCorpse(f64),
    AddMaggot(f64),
    AddCorpseAndMaggot {
        corpse: f64,
        maggot: f64,
    },
    ReduceFoodAndAddCorpse {
        food: f64,
        corpse: f64,
    },
    TemporaryPrimaryProduction {
        coins_per_second: f64,
        wood_per_second: f64,
        stone_per_second: f64,
        duration_ms: f64,
    },
    TemporaryResourceFlow {
        food_per_second: f64,
        maggot_per_second: f64,
        duration_ms: f64,
    },
    AddCorpseWithTemporaryPrimaryPenalty {
        corpse: f64,
        coins_per_second: f64,
        wood_per_second: f64,
        stone_per_second: f64,
        duration_ms: f64,
    },
    ReduceFoodAndAddCorpseWithAftershock {
        food: f64,
        corpse: f64,
        food_per_second: f64,
        maggot_per_second: f64,
        duration_ms: f64,
    },
}

#[derive(Clone, Copy)]
pub(super) struct StageSubject {
    pub(super) code: &'static str,
    pub(super) category: EventCategory,
    pub(super) trigger: TriggerFamily,
    pub(super) focus_zh: &'static str,
    pub(super) focus_en: &'static str,
    pub(super) angle_zh: &'static str,
    pub(super) angle_en: &'static str,
    pub(super) result_zh: &'static str,
    pub(super) result_en: &'static str,
    pub(super) impact: EventImpact,
    pub(super) effect: EventEffect,
    pub(super) breaking: bool,
}

#[derive(Clone, Copy)]
pub(super) struct TechTopic {
    pub(super) code: &'static str,
    pub(super) technology: TechnologyId,
    pub(super) category: EventCategory,
    pub(super) focus_zh: &'static str,
    pub(super) focus_en: &'static str,
    pub(super) angle_zh: &'static str,
    pub(super) angle_en: &'static str,
    pub(super) result_zh: &'static str,
    pub(super) result_en: &'static str,
    pub(super) breaking: bool,
}

#[derive(Clone)]
pub(super) struct ScenarioSeed {
    pub(super) id: String,
    pub(super) category: EventCategory,
    pub(super) impact: EventImpact,
    pub(super) stage: GameStage,
    pub(super) required_technology: Option<TechnologyId>,
    pub(super) trigger: TriggerFamily,
    pub(super) focus_zh: &'static str,
    pub(super) focus_en: &'static str,
    pub(super) desk_zh: &'static str,
    pub(super) desk_en: &'static str,
    pub(super) angle_zh: &'static str,
    pub(super) angle_en: &'static str,
    pub(super) result_zh: &'static str,
    pub(super) result_en: &'static str,
    pub(super) effect: EventEffect,
    pub(super) breaking: bool,
}

pub(super) const BASE_DESKS: [(&str, &str); 4] = [
    ("本台讯", "Breaking Desk"),
    ("深度报道", "Long Read"),
    ("聚落日报", "Settlement Daily"),
    ("工务快线", "Operations Wire"),
];

pub(super) const TECH_DESKS: [(&str, &str); 2] = [
    ("产业前沿", "Industry Brief"),
    ("系统简报", "System Bulletin"),
];

pub(super) const CULTURE_DESKS: [(&str, &str); 4] = [
    ("街区文娱", "Culture Desk"),
    ("夜报副刊", "After Hours"),
    ("流行观察", "Trending Watch"),
    ("周末特刊", "Weekend Feature"),
];

pub(super) const RUMOR_DESKS: [(&str, &str); 4] = [
    ("夜班怪谈", "Night Rumor File"),
    ("传闻记录", "Rumor Ledger"),
    ("边角消息", "Whisper Wire"),
    ("深夜来信", "Midnight Dispatch"),
];

pub(super) const TEMPLATE_EXPANSION_FACTOR: usize = 5;
pub(super) const REPORT_VARIANT_COUNT: usize = 1000;
pub(super) const EVENT_TEMPLATE_CAPACITY: usize = 1800;

const GENESIS_STAGE_SUBJECTS: [StageSubject; 12] = [
    StageSubject { code: "click_heat", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "点击热度升温", focus_en: "click-heat surge", angle_zh: "最初的手工经济正在被反复点击推到极限边缘。", angle_en: "The earliest manual economy is being pushed to its edge by relentless clicking.", result_zh: "聚落第一次开始像一个会主动加速的系统。", result_en: "The settlement is beginning to behave like a system that can accelerate itself.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "ledger_noise", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::Baseline, focus_zh: "台账噪声增加", focus_en: "ledger noise rises", angle_zh: "早期资源记录出现越来越多的修订痕迹，说明节拍正在加快。", angle_en: "Early resource ledgers are showing more revisions, a sign that pace is increasing.", result_zh: "数字还小，但管理压力已经先一步浮现。", result_en: "The numbers remain small, but management pressure is already surfacing.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "supply_corners", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "补给角变成临时舞台", focus_en: "supply corner turns into an impromptu stage", angle_zh: "有人在堆满木料和矿石的补给角唱起了小调，结果围观的人比领料的人还多。", angle_en: "Someone started singing beside a supply corner stacked with timber and ore, and soon the audience outnumbered the people collecting materials.", result_zh: "最简陋的角落也开始生长出花边新闻。", result_en: "Even the roughest corner is beginning to generate tabloid material.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "starter_rumor", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "起步扩张传闻", focus_en: "starter expansion rumor", angle_zh: "关于“下一轮建造会更快”的说法已经在工棚里流传。", angle_en: "Talk of the next build wave moving faster is already circulating through the bunk rows.", result_zh: "扩张在真正发生前，先以传闻形态出现。", result_en: "Expansion appears first as rumor before it arrives as fact.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "starter_patch", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "临时补给包下发", focus_en: "starter supply patch", angle_zh: "一次临时补给让最早期的扩张线路短暂变得更顺。", angle_en: "A temporary supply patch made the very first expansion lane briefly smoother.", result_zh: "这只是过渡性修正，并不会长期改变主线节拍。", result_en: "It is only a transitional correction and will not permanently rewrite the pacing line.", impact: EventImpact::Flavor, effect: EventEffect::TemporaryPrimaryProduction { coins_per_second: 1.2, wood_per_second: 0.8, stone_per_second: 0.8, duration_ms: 90_000.0 }, breaking: true },
    StageSubject { code: "tool_scarcity", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "简陋工具短缺", focus_en: "improvised tool shortage", angle_zh: "最早一批工具开始在高频使用下显出疲态，点击经济第一次碰到物理边界。", angle_en: "The earliest improvised tools are showing fatigue under high use, giving the click economy its first physical limit.", result_zh: "原始扩张开始要求真正的后勤意识。", result_en: "Primitive expansion is beginning to demand genuine logistical awareness.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "mud_route", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "泥地运输线成形", focus_en: "mud-track hauling lane", angle_zh: "松散踩出的运输路线正在把资源堆场和建造点连成固定通道。", angle_en: "A loose foot-beaten hauling lane is turning stockpiles and work sites into a fixed corridor.", result_zh: "聚落第一次显出基础设施的轮廓。", result_en: "The settlement is showing the outline of infrastructure for the first time.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "salvage_fair", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "拾荒市集开张", focus_en: "salvage fair opens", angle_zh: "一场围绕木料、矿石和旧工具的临时集市在营地中央自发出现，还意外吸引了整片工棚围观。", angle_en: "A makeshift market for timber, ore, and scavenged tools has sprung up in the middle of camp, drawing curious crowds from the bunk rows.", result_zh: "最早期的娱乐和交易第一次混在一起，营地开始像个真正活着的社会。", result_en: "Entertainment and trade are mixing for the first time, making the camp feel like a living society instead of a worksite alone.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "mud_comedian", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "泥地脱口秀突然走红", focus_en: "mud-yard comedy act takes off", angle_zh: "有人把一天里最荒唐的失误编成段子在泥地边表演，结果笑声大到把附近的值守都引了过来。", angle_en: "Someone turned the day's worst mistakes into a crude comedy routine by the mud track, and the laughter got loud enough to draw in nearby watch crews.", result_zh: "在最缺秩序的时候，聚落反而学会了制造娱乐。", result_en: "At the very moment order is most scarce, the settlement is learning to manufacture entertainment.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "campfire_legend", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "篝火旁的井底怪声", focus_en: "campfire well-whisper legend", angle_zh: "夜里有人发誓听见废井深处传来像人又不像人的回声，这条故事正在篝火边越讲越离谱。", angle_en: "Several workers swear they heard an almost-human echo rising from the abandoned well, and the story is becoming wilder with each retelling around the fire.", result_zh: "聚落还很简陋，但都市传说已经先一步长出来了。", result_en: "The settlement remains crude, but urban legend has already arrived ahead of proper streets.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "watch_betting", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "值守轮盘赌流行", focus_en: "watch rotation betting catches on", angle_zh: "有人开始偷偷押注哪一组工人会最先在夜班撑不住，结果这件坏笑话迅速变成了整片营地的娱乐。", angle_en: "Workers have started quietly betting on which crew will crack first on night watch, and the cruel joke has somehow become camp-wide entertainment.", result_zh: "最早期的社会已经学会从压力里提炼出低俗乐子。", result_en: "Even the earliest society has learned how to squeeze low humor out of pressure.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "dry_storage_ghost", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "干燥储区闹鬼说疯传", focus_en: "dry storage ghost rumor spreads", angle_zh: "有人声称新搭起来的干燥储区每到半夜都会自己发出敲击声，这则怪谈让看守工人宁愿绕远路也不肯独自靠近。", angle_en: "Workers insist the new dry-storage sheds knock on their own after midnight, and the ghost story has guards taking the long route rather than walking past alone.", result_zh: "哪怕只是储物棚，聚落也会把它讲成怪谈现场。", result_en: "Even a storage shed can turn into a ghost story once the settlement starts narrating itself that way.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
];

const WORKERS_STAGE_SUBJECTS: [StageSubject; 12] = [
    StageSubject { code: "ration_line", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::FoodStress, focus_zh: "配给线拉长", focus_en: "ration lines stretch", angle_zh: "食物与人口开始互相拖拽，补给窗口前的停顿比昨天更长。", angle_en: "Food and population are beginning to pull against each other, and the ration window pauses are longer than yesterday.", result_zh: "这说明工人阶段已经真正进入供养逻辑。", result_en: "It confirms the worker stage has fully entered its sustenance logic.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "housing_push", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "住房扩建催促", focus_en: "housing expansion pressure", angle_zh: "居住容量和岗位数量第一次开始彼此牵制。", angle_en: "Housing capacity and job volume are constraining one another for the first time.", result_zh: "玩家已无法只靠资源堆量无脑推进。", result_en: "The player can no longer brute-force progress through resource stacking alone.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "canteen_heat", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::FoodStress, focus_zh: "食堂热区拥堵", focus_en: "canteen hot-zone congestion", angle_zh: "换班时段的热食需求开始挤压正常生产节拍。", angle_en: "Hot-meal demand during shift changes is beginning to squeeze the normal production rhythm.", result_zh: "后勤正在成为主系统，而不是附属系统。", result_en: "Logistics is becoming a primary system rather than a support system.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "overtime_forms", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::Baseline, focus_zh: "加班表格泛滥", focus_en: "overtime forms proliferate", angle_zh: "岗位、住房和食物第一次被写进同一份调度表。", angle_en: "Jobs, housing, and food are being written into the same dispatch sheet for the first time.", result_zh: "聚落正式进入人口驱动的管理期。", result_en: "The settlement has formally entered population-driven management.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "worker_strike", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::FoodStress, focus_zh: "加班工人爆发短暂停工", focus_en: "overtime crews stage a short walkout", angle_zh: "因为连日超时工作和配给缩水，部分高压岗位的工人突然拒绝继续开工，现场一度陷入僵持。", angle_en: "After repeated overtime and shrinking rations, workers in several high-pressure roles abruptly refused to continue, briefly freezing the floor in place.", result_zh: "这不再只是抱怨，而是劳工冲突第一次真正浮上台面。", result_en: "This is no longer mere complaint; organized labor conflict has surfaced for the first time.", impact: EventImpact::Flavor, effect: EventEffect::TemporaryPrimaryProduction { coins_per_second: -1.4, wood_per_second: -0.8, stone_per_second: -0.8, duration_ms: 90_000.0 }, breaking: true },
    StageSubject { code: "granary_failure", category: EventCategory::DarkConversion, trigger: TriggerFamily::FoodGlutStall, focus_zh: "余粮腐败事故", focus_en: "surplus grain rot incident", angle_zh: "过剩食物在封存环境中转为一次真正的腐败事故，留下了难以解释的遗留物。", angle_en: "Surplus food inside sealed storage tipped into a real rot incident, leaving behind residue nobody can explain cleanly.", result_zh: "这类事故会把被掩盖的黑暗链条重新推到台前。", result_en: "Incidents like this pull the hidden dark chain back into view.", impact: EventImpact::Effective, effect: EventEffect::ReduceFoodAndAddCorpseWithAftershock { food: 8.0, corpse: 1.0, food_per_second: -0.5, maggot_per_second: 0.15, duration_ms: 120_000.0 }, breaking: true },
    StageSubject { code: "nursery_pageant", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "临时育儿区办起评选秀", focus_en: "nursery corner pageant takes off", angle_zh: "临时照料区里一场给婴儿和看护工人办的小评选居然成了最受欢迎的下班节目。", angle_en: "A tiny pageant for babies and caretakers inside the temporary nursery has somehow become the settlement's most popular after-shift diversion.", result_zh: "人口压力之外，生活本身也开始制造自己的头条。", result_en: "Beyond population pressure, life itself is starting to generate its own headlines.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "kitchen_audit", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::FoodStress, focus_zh: "厨房审计传闻", focus_en: "kitchen audit rumor", angle_zh: "关于谁在提前消耗储备的争论把食物管理第一次推上公开台账。", angle_en: "Arguments about who is consuming reserves early are forcing food management into the open ledger for the first time.", result_zh: "供养链开始生成自己的政治。", result_en: "The sustenance chain is generating its own politics.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "factory_accident", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::FoodStress, focus_zh: "工厂重大事故致多人死伤", focus_en: "major factory accident leaves multiple casualties", angle_zh: "一次连锁失误把高温工位、运输带和夜班疲劳同时卷进同一场事故，数名工人受伤，另有多人当场死亡。", angle_en: "A chain of failures pulled a hot station, conveyor lane, and exhausted night crew into the same disaster, injuring several workers and killing others on site.", result_zh: "工人阶段第一次以真正的工业事故口吻被写进新闻。", result_en: "The worker stage is being written in the language of real industrial disaster for the first time.", impact: EventImpact::Effective, effect: EventEffect::AddCorpseWithTemporaryPrimaryPenalty { corpse: 2.0, coins_per_second: -1.8, wood_per_second: -0.9, stone_per_second: -0.9, duration_ms: 90_000.0 }, breaking: true },
    StageSubject { code: "canteen_festival", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "夜班食堂节意外爆红", focus_en: "night canteen festival draws a crowd", angle_zh: "有人把原本单调的换班晚餐办成了带表演和小游戏的食堂活动，意外收获了整片宿舍区的欢迎。", angle_en: "What began as an ordinary shift-change supper turned into a canteen event with performances and games, unexpectedly becoming the most popular gathering in the dorm district.", result_zh: "在疲惫和饥饿之间，娱乐第一次被当成真正的公共需求。", result_en: "Between fatigue and hunger, entertainment is being recognized as a genuine public need.", impact: EventImpact::Flavor, effect: EventEffect::TemporaryResourceFlow { food_per_second: 0.75, maggot_per_second: 0.0, duration_ms: 90_000.0 }, breaking: false },
    StageSubject { code: "night_shift_romance", category: EventCategory::SocialMutation, trigger: TriggerFamily::Baseline, focus_zh: "夜班恋爱八卦登上墙报", focus_en: "night shift romance gossip hits the wall sheet", angle_zh: "一段关于夜班运输工和食堂帮工的绯闻莫名其妙被写进了手绘小报，围观程度甚至短暂压过了当天的加班争议。", angle_en: "Rumors of a romance between a night-haul worker and a canteen hand somehow made it onto a hand-drawn sheet, briefly drawing more attention than the day's overtime dispute.", result_zh: "再苦的工人阶段，也总有人把八卦活成头版。", result_en: "However harsh the worker stage becomes, someone will still turn gossip into a front page.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "reserve_pest", category: EventCategory::DarkConversion, trigger: TriggerFamily::FoodGlutStall, focus_zh: "储备区异虫传闻", focus_en: "reserve-bay larvae rumor", angle_zh: "过多食物在阴湿角落里引出不该出现的幼体活动，后勤组开始紧张。", angle_en: "Excess food in damp corners is provoking larval activity that should not exist, and logistics crews are growing tense.", result_zh: "丰收第一次变成通向黑暗链条的入口。", result_en: "Abundance is becoming an entrance into the dark chain for the first time.", impact: EventImpact::Effective, effect: EventEffect::AddMaggot(6.0), breaking: true },
];

const MAGGOT_STAGE_SUBJECTS: [StageSubject; 12] = [
    StageSubject { code: "decay_watch", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "腐化带监测升级", focus_en: "decay-zone watch escalates", angle_zh: "尸体与异动幼体已经不再被当作偶发异常处理。", angle_en: "Bodies and larval anomalies are no longer being treated as isolated incidents.", result_zh: "黑暗生产链从事故转向制度。", result_en: "The dark production chain is moving from accident to institution.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "pit_bulletin", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "育池播报增加", focus_en: "breeding-pit bulletins rise", angle_zh: "与蛆虫相关的内部通报正在从秘密记录变成正式运营语言。", angle_en: "Internal notices tied to maggot handling are shifting from secret records to official operating language.", result_zh: "一条曾被回避的链条，正在获得自己的术语。", result_en: "A chain that was once avoided is gaining its own vocabulary.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "cleanup_lobby", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::DarkSignal, focus_zh: "清理组扩编争议", focus_en: "cleanup crew expansion dispute", angle_zh: "围绕谁来处理黑暗链条外溢物的争论越来越公开。", angle_en: "Debates over who should handle dark-chain spillover are becoming increasingly public.", result_zh: "新的产业正在制造新的岗位与新的恐惧。", result_en: "A new industry is creating new jobs and new fears at the same time.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "rot_editorial", category: EventCategory::SocialMutation, trigger: TriggerFamily::DarkSignal, focus_zh: "腐化社论连载", focus_en: "rot editorial serial", angle_zh: "聚落墙报开始把黑暗生产写成“不可回避的第二条经济”。", angle_en: "Wall editors are beginning to describe dark production as the unavoidable second economy.", result_zh: "社会已经开始用解释而不是否认来面对它。", result_en: "Society is beginning to explain it instead of deny it.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "drain_burst", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "排污渠回流", focus_en: "drain-channel reflux", angle_zh: "一轮回流把可利用的腐化样本重新带回主流程，使黑暗资源短时暴增。", angle_en: "A reflux cycle pushed reusable corrupted samples back into the main flow, causing a short spike in dark material.", result_zh: "这种异常会直接改写黑暗链条的供给速度。", result_en: "Anomalies like this directly rewrite the feed speed of the dark chain.", impact: EventImpact::Effective, effect: EventEffect::AddMaggot(12.0), breaking: true },
    StageSubject { code: "bone_sorting", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "骨料分拣开始", focus_en: "bone sorting begins", angle_zh: "尸体副产物第一次被拆分为不同处理流，黑暗工艺变得更像工业流程。", angle_en: "Corpse byproducts are being split into separate treatment flows for the first time, making dark craft look more industrial.", result_zh: "黑暗链条正在失去“临时性”的外衣。", result_en: "The dark chain is shedding its temporary disguise.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "pit_collapse", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "育池坍塌致多人死伤", focus_en: "breeding pit collapse injures and kills several", angle_zh: "一段临时加固失败的育池边缘突然坍塌，清理工与看守人员被同时卷入，现场留下了大量无法立即处理的残骸。", angle_en: "A poorly reinforced edge of the breeding pit collapsed without warning, dragging both cleanup hands and watch staff into the fall and leaving behind remains that could not be cleared immediately.", result_zh: "黑暗链条第一次拥有了足以让整座聚落沉默的重大事故。", result_en: "The dark chain has produced its first major disaster serious enough to silence the entire settlement.", impact: EventImpact::Effective, effect: EventEffect::AddCorpseAndMaggot { corpse: 2.0, maggot: 10.0 }, breaking: true },
    StageSubject { code: "maggot_market", category: EventCategory::SocialMutation, trigger: TriggerFamily::DarkSignal, focus_zh: "蛆虫夜市意外火爆", focus_en: "maggot night market unexpectedly booms", angle_zh: "围绕异常幼体的交易、表演和猎奇摊位居然在夜里拼成了一个畸形又热闹的小夜市。", angle_en: "Trade, spectacle, and curiosity stalls built around larval anomalies have somehow fused into a grotesque but wildly popular night market.", result_zh: "黑暗资源不只生成灰市，也开始生成低俗娱乐。", result_en: "Dark resources are no longer just feeding grey markets; they are feeding vulgar entertainment too.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "pit_idol", category: EventCategory::SocialMutation, trigger: TriggerFamily::DarkSignal, focus_zh: "育池偶像评选荒诞登场", focus_en: "breeding-pit idol contest turns absurd", angle_zh: "有人居然给清理工和育池看守办起了带投票的“人气评选”，整件事又荒唐又受欢迎。", angle_en: "Someone somehow launched a voted popularity contest for cleanup crews and pit watchers, and the whole thing is both absurd and wildly popular.", result_zh: "黑暗链条连同低俗娱乐一起开始制度化。", result_en: "The dark chain is becoming institutionalized alongside its own vulgar celebrity culture.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "incinerator_debate", category: EventCategory::SocialMutation, trigger: TriggerFamily::DarkSignal, focus_zh: "焚化派与回收派争执", focus_en: "incinerate-versus-recycle dispute", angle_zh: "围绕尸体该被销毁还是回收的争论开始占据公开讨论版面。", angle_en: "Arguments over whether bodies should be destroyed or recycled are taking over public discussion boards.", result_zh: "黑暗链条第一次迫使社会公开表态。", result_en: "The dark chain is forcing public alignment for the first time.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "larvae_bloom", category: EventCategory::DarkConversion, trigger: TriggerFamily::DarkSignal, focus_zh: "幼体暴涨日", focus_en: "larval bloom day", angle_zh: "一次异常温湿变化让幼体数量突然跃升，处理线被迫临时改班。", angle_en: "A sudden temperature-humidity swing has pushed larval counts sharply upward, forcing emergency shift changes.", result_zh: "黑暗资源的增长第一次显得像天气，而不是库存。", result_en: "Dark resource growth is beginning to feel like weather rather than inventory.", impact: EventImpact::Effective, effect: EventEffect::AddCorpseAndMaggot { corpse: 1.0, maggot: 8.0 }, breaking: true },
    StageSubject { code: "sewer_corpse_legend", category: EventCategory::SocialMutation, trigger: TriggerFamily::DarkSignal, focus_zh: "下水道尸体会动的传闻", focus_en: "rumors spread of moving bodies in the sewers", angle_zh: "越来越多人声称看见下水道里的尸体在没人靠近时自行翻动，这条都市传说正把整片夜班宿舍搅得睡不安稳。", angle_en: "More and more workers claim the bodies in the sewers shift on their own when no one is nearby, and the urban legend is keeping entire night-shift dormitories awake.", result_zh: "真正让人害怕的未必是证据，而是每个人都觉得自己可能亲眼见过。", result_en: "What terrifies people is not proof itself, but the sense that almost everyone might have seen it personally.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
];

const HYBRID_STAGE_SUBJECTS: [StageSubject; 12] = [
    StageSubject { code: "shared_meal", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "共餐秩序重排", focus_en: "shared-meal order reshuffles", angle_zh: "人类与混合人口开始在同一套供养链上争夺节拍。", angle_en: "Humans and hybrid populations are now contesting rhythm inside the same sustenance chain.", result_zh: "共生不是设定，而是会每天摩擦的现实。", result_en: "Symbiosis is no longer a premise; it is a daily friction.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "host_registry_gossip", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "宿主登记八卦满天飞", focus_en: "host registry gossip runs wild", angle_zh: "关于谁在登记表上改了谁的身份、谁又被偷偷重新归类的闲话，在混住区里传得比正式说明快得多。", angle_en: "Talk of who altered whose status on the registry and who was quietly reclassified is moving through shared quarters much faster than any official explanation.", result_zh: "共生社会连制度变动也会迅速长成八卦。", result_en: "In symbiotic society, even bureaucratic change quickly grows into gossip.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "stability_panel", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "稳定度面板争论", focus_en: "stability panel dispute", angle_zh: "共生稳定度第一次被作为公共数字张贴出来。", angle_en: "Symbiosis stability has been posted as a public number for the first time.", result_zh: "统计从这里开始带有政治重量。", result_en: "Statistics acquire political weight from this point onward.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "hybrid_matchmaking", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "混居联谊夜引爆八卦", focus_en: "shared-district mixer ignites gossip", angle_zh: "一场原本打着“缓和关系”旗号的联谊夜，最后却变成了整片混住区第二天都在讨论的八卦制造机。", angle_en: "What was meant to be a relationship-easing social mixer has turned into the gossip engine of the shared districts for the next entire day.", result_zh: "共生社会连缓和矛盾的活动也能顺手制造新的花边新闻。", result_en: "In symbiotic society, even reconciliation events generate their own tabloid afterlife.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "pressure_column", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "人类压力专栏", focus_en: "human-pressure editorial", angle_zh: "围绕人类压力是否被低估的争论连续占据墙报显眼位置。", angle_en: "Arguments about whether human pressure is being underestimated now dominate the wall press.", result_zh: "社会开始围绕共生数据组织立场。", result_en: "Society is beginning to organize itself around symbiosis metrics.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "coexistence_breach", category: EventCategory::DarkConversion, trigger: TriggerFamily::HybridFlux, focus_zh: "共居区微型破口", focus_en: "cohabitation micro-breach", angle_zh: "一次短暂事故把黑暗链条重新拖回混合居民区的日常视野。", angle_en: "A brief incident dragged the dark chain back into the daily field of the hybrid districts.", result_zh: "即使进入共生阶段，腐化也不会自动退场。", result_en: "Even in symbiosis, corruption does not quietly leave the stage.", impact: EventImpact::Effective, effect: EventEffect::AddCorpseAndMaggot { corpse: 1.0, maggot: 4.0 }, breaking: true },
    StageSubject { code: "dual_school", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "双轨教育试验", focus_en: "dual-track education trial", angle_zh: "人类与混合人口第一次被纳入同一套基础训练框架，但节奏被拆成两条轨道。", angle_en: "Humans and hybrids are entering one training framework for the first time, though the rhythm has split into two tracks.", result_zh: "共生开始从制度底层塑形。", result_en: "Symbiosis is starting to take shape from the institutional floor upward.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "hybrid_variety_show", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "共生才艺秀意外出圈", focus_en: "symbiosis talent show breaks out", angle_zh: "混住区里一场本来只想让大家放松的才艺秀，意外把唱歌、变戏法和生物发光表演一起捧上了墙报热门版。", angle_en: "A talent show meant simply to relax the shared district has accidentally pushed singing, sleight-of-hand, and bioluminescent performances onto the most-read section of the wall sheets.", result_zh: "混合社会第一次明显表现出属于自己的流行文化。", result_en: "Hybrid society is showing a popular culture that is recognizably its own.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "symbiosis_parade", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "共生巡游受到热捧", focus_en: "symbiosis parade draws huge crowds", angle_zh: "一场原本只是示范共生仪式的街区巡游，意外吸引了人类、混合体和工坊学徒一起围观欢呼。", angle_en: "What began as a demonstration of symbiotic ritual unexpectedly turned into a packed district parade cheered by humans, hybrids, and workshop apprentices alike.", result_zh: "混合社会第一次拥有了能被公开庆祝的大型活动。", result_en: "Hybrid society has, for the first time, produced a mass event people openly celebrate.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "shared_quarters_scandal", category: EventCategory::SocialMutation, trigger: TriggerFamily::HybridFlux, focus_zh: "混住区换床丑闻传开", focus_en: "shared-quarters bed swap scandal spreads", angle_zh: "几次私下调换铺位和夜间串宿被写上了墙报，结果整片混住区都开始互相猜测谁和谁正在偷偷结盟。", angle_en: "A handful of private bed swaps and late-night room changes made it onto the wall sheets, and now the whole district is guessing who is quietly aligning with whom.", result_zh: "共生社会连宿舍安排都能迅速发酵成政治花边。", result_en: "In symbiotic society, even sleeping arrangements ferment rapidly into political gossip.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "hybrid_strike_talk", category: EventCategory::SurvivalCrisis, trigger: TriggerFamily::HybridFlux, focus_zh: "高压行业爆发混合罢工", focus_en: "hybrid labor strike erupts in high-pressure sectors", angle_zh: "由于连日加班和高风险岗位分配失衡，几条关键行业产线同时出现了带有组织迹象的罢工。", angle_en: "After relentless overtime and lopsided assignment to high-risk stations, several key sectors have seen strikes that already show signs of organization.", result_zh: "共生稳定度第一次被直接翻译成停工与对抗。", result_en: "Symbiosis stability has been translated directly into stoppage and confrontation for the first time.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "spillback_quarters", category: EventCategory::DarkConversion, trigger: TriggerFamily::HybridFlux, focus_zh: "宿舍回渗事故", focus_en: "dormitory seepback incident", angle_zh: "黑暗处理线的一次回渗把居民区重新拖进资源事故现场。", angle_en: "A seepback from the dark processing line has dragged the living quarters back into a resource incident scene.", result_zh: "混合社会无法通过制度完全隔离黑暗链条。", result_en: "Hybrid society cannot fully isolate the dark chain through rules alone.", impact: EventImpact::Effective, effect: EventEffect::AddMaggot(5.0), breaking: true },
];

const COLLECTIVE_STAGE_SUBJECTS: [StageSubject; 12] = [
    StageSubject { code: "hive_channel", category: EventCategory::EndgameSign, trigger: TriggerFamily::CollectiveSignal, focus_zh: "蜂巢频道开通", focus_en: "hive channel opens", angle_zh: "共享信道让指令扩散速度远超传统行政流程。", angle_en: "Shared channels are pushing orders faster than any traditional administrative process.", result_zh: "集体意识第一次像基础设施一样运作。", result_en: "Collective consciousness is operating like infrastructure for the first time.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "spire_lottery", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "尖塔天气竞猜一夜爆红", focus_en: "spire-weather betting craze erupts", angle_zh: "有人开始用尖塔天气的颜色和脉冲频率开起了竞猜局，结果连最严肃的算力岗位都有人偷偷下注。", angle_en: "Workers have started betting on spire-weather colors and pulse frequencies, and even the sternest compute stations now have people quietly placing wagers.", result_zh: "终局时代的娱乐，已经连天气都不是旧意义上的天气。", result_en: "In the endgame era, even entertainment has weather that no longer means what weather once meant.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "upload_queue_scandal", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "上传等候名单插队风波", focus_en: "upload queue favoritism scandal", angle_zh: "有人爆料上传等候名单里出现了插队和特批，消息一出就把整张共识网络吵得像集市。", angle_en: "Leaks suggesting favoritism and line-cutting inside the upload queue have turned the consensus network into something closer to a market argument than a calm shared mind.", result_zh: "哪怕到了终局，八卦仍能轻易穿透最先进的制度。", result_en: "Even in the endgame, gossip still slips easily through the most advanced institutions.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "orbital_freight", category: EventCategory::IndustrialProgress, trigger: TriggerFamily::CollectiveSignal, focus_zh: "轨道货运进入计划表", focus_en: "orbital freight enters planning", angle_zh: "远征供给第一次被写入常规产能安排。", angle_en: "Expedition supply has entered routine capacity planning for the first time.", result_zh: "终局扩张正在脱离幻想层。", result_en: "Endgame expansion is stepping out of the realm of fantasy.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "consensus_drive", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "共识动员启动", focus_en: "consensus drive begins", angle_zh: "新的共识机制开始绕过旧式协商，直接塑造集体决定。", angle_en: "New consensus mechanisms are beginning to bypass the older bargaining rituals and shape shared decisions directly.", result_zh: "高效与危险在这里共用一条通道。", result_en: "Efficiency and danger are sharing the same channel here.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "spire_breach", category: EventCategory::DarkConversion, trigger: TriggerFamily::CollectiveSignal, focus_zh: "尖塔回流事故", focus_en: "spire reflux incident", angle_zh: "一次回流事故把暗链副产物重新泵回了集体系统下层。", angle_en: "A reflux accident pumped dark-chain byproducts back into the lower collective system.", result_zh: "即使到终局阶段，黑暗链条仍能借事故改写供给。", result_en: "Even at the endgame stage, the dark chain can still rewrite supply through incident alone.", impact: EventImpact::Effective, effect: EventEffect::AddMaggot(10.0), breaking: true },
    StageSubject { code: "drone_voting", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "无人投票回路", focus_en: "drone voting loop", angle_zh: "非人执行单元第一次被纳入正式共识流程，投票概念开始扩写。", angle_en: "Non-human execution units are entering the formal consensus process for the first time, expanding the meaning of voting.", result_zh: "政治主体的边界继续被技术推开。", result_en: "Technology is pushing outward the boundary of political subjecthood.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "alien_whisper", category: EventCategory::EndgameSign, trigger: TriggerFamily::CollectiveSignal, focus_zh: "发现外星人的传闻疯传", focus_en: "alien discovery rumors spread wildly", angle_zh: "一段被反复转录的奇怪信号让整座聚落都在讨论：远征队到底是发现了外星生命，还是只是碰到了会说话的回声。", angle_en: "A strange repeatedly transcribed signal has the whole settlement arguing over whether the expedition found alien life or merely an echo clever enough to talk back.", result_zh: "终局时代连小道消息都开始拥有宇宙尺度。", result_en: "In the endgame era, even gossip has begun to acquire a cosmic scale.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "relay_blackout_gossip", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "中继失明夜里的离奇目击", focus_en: "strange sightings during the relay blackout", angle_zh: "在那场短暂失明里，越来越多人声称看见并不存在的人影、听见不属于任何人的第二道呼吸。", angle_en: "During the brief blackout, more and more residents claimed to see figures that were not there and hear a second breath that belonged to no one at all.", result_zh: "终局社会连系统故障都能迅速长成半宗教式怪谈。", result_en: "In endgame society, even a systems failure can mutate almost instantly into a quasi-religious rumor cycle.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: true },
    StageSubject { code: "hive_art", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "群体艺术节引发狂热", focus_en: "collective arts festival sparks frenzy", angle_zh: "共享网络产出的合唱、影像和梦境剧场被办成大型艺术节，观众多到把整片通道堵成了缓慢流动的人潮。", angle_en: "Choral works, visuals, and dream-theatre pieces produced by the shared network have been turned into a major arts festival that drew crowds dense enough to clog entire corridors.", result_zh: "终局社会第一次出现了真正意义上的全民娱乐事件。", result_en: "Endgame society has produced its first genuinely mass entertainment event.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "orbit_gala", category: EventCategory::SocialMutation, trigger: TriggerFamily::CollectiveSignal, focus_zh: "轨道观景夜成上流新宠", focus_en: "orbital viewing gala becomes elite obsession", angle_zh: "围绕发射窗口搭建的观景夜和远征倒计时晚会，已经开始把终局社会分出新的体面与炫耀方式。", angle_en: "Viewing nights built around launch windows and expedition countdown galas are beginning to create fresh hierarchies of prestige and display in endgame society.", result_zh: "终局不只会生产技术，也会生产新的虚荣。", result_en: "The endgame produces not only technology, but new forms of vanity.", impact: EventImpact::Flavor, effect: EventEffect::None, breaking: false },
    StageSubject { code: "consensus_riot", category: EventCategory::DarkConversion, trigger: TriggerFamily::CollectiveSignal, focus_zh: "共识回响失控", focus_en: "consensus feedback runaway", angle_zh: "一次失控回响把集体信号和暗链副产物短暂耦合，留下危险沉积。", angle_en: "A runaway feedback cycle briefly coupled collective signals with dark-chain byproducts, leaving dangerous residue.", result_zh: "终局系统越高阶，事故越像生态级事件。", result_en: "The higher the endgame system climbs, the more each accident resembles an ecological event.", impact: EventImpact::Effective, effect: EventEffect::AddCorpseAndMaggot { corpse: 1.0, maggot: 6.0 }, breaking: true },
];

const GENESIS_TECH_TOPICS: [TechTopic; 12] = [
    TechTopic { code: "basic_mining", technology: TechnologyId::BasicMining, category: EventCategory::IndustrialProgress, focus_zh: "基础采矿专栏", focus_en: "basic mining column", angle_zh: "矿脉勘探第一次被写成公开的扩张方法论。", angle_en: "Ore scouting is being written into a public expansion methodology for the first time.", result_zh: "点击经济开始拥有系统化的地基层。", result_en: "The click economy is gaining a systematic material base.", breaking: false },
    TechTopic { code: "advanced_mining", technology: TechnologyId::AdvancedMining, category: EventCategory::IndustrialProgress, focus_zh: "高级采矿快讯", focus_en: "advanced mining flash", angle_zh: "更深层矿脉的叙事开始进入聚落日常。", angle_en: "Narratives about deeper veins are entering settlement routine.", result_zh: "前期扩张第一次露出真正的资源野心。", result_en: "Early expansion is showing real resource ambition.", breaking: false },
    TechTopic { code: "basic_logging", technology: TechnologyId::BasicLogging, category: EventCategory::IndustrialProgress, focus_zh: "基础伐木报道", focus_en: "basic logging report", angle_zh: "木材供应终于被视作可规划的产业，而非随手砍伐。", angle_en: "Wood supply is finally being treated as a planned industry rather than casual chopping.", result_zh: "资源开始从临时采集转向标准流程。", result_en: "Resources are shifting from opportunistic gathering to standard procedure.", breaking: false },
    TechTopic { code: "advanced_logging", technology: TechnologyId::AdvancedLogging, category: EventCategory::IndustrialProgress, focus_zh: "高级伐木观察", focus_en: "advanced logging watch", angle_zh: "更高效的林区切割正在改变建筑扩张的节拍。", angle_en: "More efficient timber cutting is changing the rhythm of building expansion.", result_zh: "聚落第一次感到材料储备能领先于需求。", result_en: "The settlement is, for the first time, feeling materials run ahead of demand.", breaking: false },
    TechTopic { code: "basic_quarrying", technology: TechnologyId::BasicQuarrying, category: EventCategory::IndustrialProgress, focus_zh: "基础采石纪要", focus_en: "basic quarrying memo", angle_zh: "石料被重新定义为城市骨架的一部分。", angle_en: "Stone is being redefined as part of the city's skeleton.", result_zh: "建筑节奏将因此更稳定也更坚硬。", result_en: "Building cadence is about to become both steadier and harder.", breaking: false },
    TechTopic { code: "click_efficiency", technology: TechnologyId::ClickEfficiency, category: EventCategory::IndustrialProgress, focus_zh: "点击效率社论", focus_en: "click efficiency editorial", angle_zh: "手工点击本身被重新包装成早期经济的关键技能。", angle_en: "Manual clicking itself is being reframed as a critical skill in the early economy.", result_zh: "哪怕最原始的行为，也开始被制度化。", result_en: "Even the most primitive action is being institutionalized now.", breaking: false },
    TechTopic { code: "advanced_quarrying", technology: TechnologyId::AdvancedQuarrying, category: EventCategory::IndustrialProgress, focus_zh: "高级采石通报", focus_en: "advanced quarrying advisory", angle_zh: "更深层石料切割让聚落第一次拥有真正可预估的硬质骨架。", angle_en: "Deeper stone cutting is giving the settlement a genuinely predictable hard-frame supply for the first time.", result_zh: "基础建设开始压低临时修补的频率。", result_en: "Core construction is starting to reduce the need for emergency patchwork.", breaking: false },
    TechTopic { code: "advanced_agriculture", technology: TechnologyId::AdvancedAgriculture, category: EventCategory::SurvivalCrisis, focus_zh: "高级农业观察", focus_en: "advanced agriculture watch", angle_zh: "更精细的农业技术第一次让“稳定供养”看起来像是可实现目标。", angle_en: "More refined agricultural methods are making stable sustenance look achievable for the first time.", result_zh: "食物将从焦虑来源转向扩张底盘。", result_en: "Food is beginning to shift from anxiety source into expansion base.", breaking: false },
    TechTopic { code: "basic_refining", technology: TechnologyId::BasicRefining, category: EventCategory::IndustrialProgress, focus_zh: "基础精炼短讯", focus_en: "basic refining brief", angle_zh: "原料第一次被大规模送入去杂与提纯流程，而非直接投入建造。", angle_en: "Raw material is entering purification flow at scale instead of going straight into construction for the first time.", result_zh: "资源链开始学会提前加工。", result_en: "The resource chain is learning to preprocess itself.", breaking: false },
    TechTopic { code: "resource_boost", technology: TechnologyId::ResourceBoost, category: EventCategory::IndustrialProgress, focus_zh: "资源增益专栏", focus_en: "resource boost column", angle_zh: "关于如何把最早期资源线榨出更多回报的讨论突然变得系统化。", angle_en: "Discussion of how to squeeze more yield out of the earliest resource lines has suddenly become systematic.", result_zh: "聚落开始真正理解“效率”这个词。", result_en: "The settlement is beginning to understand what efficiency actually means.", breaking: false },
    TechTopic { code: "cost_reduction", technology: TechnologyId::CostReduction, category: EventCategory::IndustrialProgress, focus_zh: "成本削减评论", focus_en: "cost reduction commentary", angle_zh: "减少浪费第一次被当成和获取资源同等重要的技术方向。", angle_en: "Waste reduction is being treated as a technical direction as important as acquisition itself.", result_zh: "节流第一次加入早期扩张语法。", result_en: "Conservation is entering the grammar of early expansion.", breaking: false },
    TechTopic { code: "critical_click", technology: TechnologyId::CriticalClick, category: EventCategory::IndustrialProgress, focus_zh: "暴击点击快报", focus_en: "critical click flash", angle_zh: "高强度手工操作偶尔爆发出的极值收益开始被写成可追求现象。", angle_en: "Peak returns from intense manual action are now being written up as a phenomenon worth pursuing.", result_zh: "最原始的劳动突然拥有了赌性与戏剧性。", result_en: "The most primitive labor has suddenly gained risk, luck, and spectacle.", breaking: true },
];

const WORKERS_TECH_TOPICS: [TechTopic; 12] = [
    TechTopic { code: "basic_smelting", technology: TechnologyId::BasicSmelting, category: EventCategory::IndustrialProgress, focus_zh: "基础冶炼上线", focus_en: "basic smelting goes live", angle_zh: "矿石终于第一次被写进加工链条，而不是只停留在原料清单。", angle_en: "Ore is entering the processing chain for the first time instead of staying on a raw ledger.", result_zh: "工业阶段的骨架已经竖起来了。", result_en: "The skeleton of the industrial stage is up now.", breaking: false },
    TechTopic { code: "basic_agriculture", technology: TechnologyId::BasicAgriculture, category: EventCategory::SurvivalCrisis, focus_zh: "基础农业专报", focus_en: "basic agriculture bulletin", angle_zh: "食物供给第一次拥有了真正意义上的技术背书。", angle_en: "Food supply has, for the first time, gained real technical backing.", result_zh: "供养问题开始有了可扩大的解法。", result_en: "Sustenance is beginning to look scalable rather than improvised.", breaking: false },
    TechTopic { code: "basic_chemistry", technology: TechnologyId::BasicChemistry, category: EventCategory::IndustrialProgress, focus_zh: "基础化学简讯", focus_en: "basic chemistry note", angle_zh: "新的化学链条让工人阶段第一次闻到更复杂工业的味道。", angle_en: "New chemical lines are giving the worker stage its first scent of more complex industry.", result_zh: "加工材料从这里开始真正分层。", result_en: "Processed materials begin to tier up from this point forward.", breaking: false },
    TechTopic { code: "automation", technology: TechnologyId::Automation, category: EventCategory::IndustrialProgress, focus_zh: "自动化通告", focus_en: "automation notice", angle_zh: "重复劳动第一次被写进可以主动剥离的人类工作名单。", angle_en: "Repetitive labor is entering the list of tasks that can be actively peeled away from human hands.", result_zh: "工人系统即将从数量管理转向效率管理。", result_en: "The worker system is about to shift from counting bodies to managing efficiency.", breaking: true },
    TechTopic { code: "electronics", technology: TechnologyId::Electronics, category: EventCategory::IndustrialProgress, focus_zh: "电子技术栏", focus_en: "electronics column", angle_zh: "线路与晶体第一次把工厂叙事拉向更精密的方向。", angle_en: "Circuits and crystals are pulling the factory narrative toward higher precision for the first time.", result_zh: "更高阶工艺开始拥有现实入口。", result_en: "Higher-order processes have found a practical entrance.", breaking: false },
    TechTopic { code: "auto_assignment", technology: TechnologyId::AutoAssignment, category: EventCategory::IndustrialProgress, focus_zh: "自动分配观察", focus_en: "auto-assignment watch", angle_zh: "岗位分配开始从人为拖动转向收益排序。", angle_en: "Job assignment is moving from manual dragging toward yield-based ordering.", result_zh: "调度逻辑第一次成为可见机制。", result_en: "Dispatch logic has become a visible mechanic at last.", breaking: false },
    TechTopic { code: "advanced_smelting", technology: TechnologyId::AdvancedSmelting, category: EventCategory::IndustrialProgress, focus_zh: "高级冶炼简报", focus_en: "advanced smelting brief", angle_zh: "冶炼线开始从粗放转向稳定，高热工位被第一次系统整编。", angle_en: "The smelting line is shifting from rough throughput toward stable processing, and high-heat stations are being systematically reorganized.", result_zh: "金属资源链正在形成更长的工业脊梁。", result_en: "The metal chain is building a longer industrial spine.", breaking: false },
    TechTopic { code: "mass_production", technology: TechnologyId::MassProduction, category: EventCategory::IndustrialProgress, focus_zh: "量产制度观察", focus_en: "mass production watch", angle_zh: "批量流程第一次明确压过手工补丁，工人阶段开始看到工业级秩序。", angle_en: "Batch process is decisively overtaking hand-made patchwork, giving the worker stage its first view of industrial order.", result_zh: "人海战术正被流程战术替代。", result_en: "Body-count tactics are yielding to process tactics.", breaking: false },
    TechTopic { code: "robotics", technology: TechnologyId::Robotics, category: EventCategory::IndustrialProgress, focus_zh: "机器人技术侧栏", focus_en: "robotics sidebar", angle_zh: "半自动岗位开始试探性进入车间，重新定义人手短缺的含义。", angle_en: "Semi-automated stations are entering the workshop on a trial basis and redefining what labor shortage means.", result_zh: "工人系统第一次感到替代性压力。", result_en: "The worker system is feeling substitution pressure for the first time.", breaking: false },
    TechTopic { code: "computer_technology", technology: TechnologyId::ComputerTechnology, category: EventCategory::IndustrialProgress, focus_zh: "计算机技术纪要", focus_en: "computer technology memorandum", angle_zh: "调度、记录和预测第一次被拉进同一套计算框架。", angle_en: "Dispatch, recordkeeping, and forecasting are entering one computing framework for the first time.", result_zh: "管理层开始拥有真正的前瞻工具。", result_en: "Management is acquiring a genuine forward-looking toolset.", breaking: false },
    TechTopic { code: "ai_technology", technology: TechnologyId::AITechnology, category: EventCategory::IndustrialProgress, focus_zh: "人工智能前哨", focus_en: "AI technology outpost", angle_zh: "最初级的自动判断系统已经开始介入排产与误差修正。", angle_en: "The earliest automated judgment systems are entering scheduling and error correction.", result_zh: "生产线第一次拥有非人决策辅助。", result_en: "The line has acquired non-human decision support for the first time.", breaking: true },
    TechTopic { code: "advanced_electronics", technology: TechnologyId::AdvancedElectronics, category: EventCategory::IndustrialProgress, focus_zh: "高级电子深描", focus_en: "advanced electronics profile", angle_zh: "更精细的电路开始把工人阶段与高阶工业直接短接。", angle_en: "More refined circuitry is directly short-connecting the worker stage to higher industry.", result_zh: "复杂工艺终于拥有了常规入口。", result_en: "Complex process now has a routine entrance.", breaking: false },
];

const MAGGOT_TECH_TOPICS: [TechTopic; 12] = [
    TechTopic { code: "maggot_breeding", technology: TechnologyId::MaggotBreeding, category: EventCategory::DarkConversion, focus_zh: "蛆虫育种专栏", focus_en: "maggot breeding column", angle_zh: "黑暗链条第一次拥有了公开可讨论的技术名目。", angle_en: "The dark chain now has a technical label that can be discussed in public.", result_zh: "事故终于被包装成工艺。", result_en: "An accident has been packaged into a process.", breaking: true },
    TechTopic { code: "necrotic_recycling", technology: TechnologyId::NecroticRecycling, category: EventCategory::DarkConversion, focus_zh: "坏死回收报道", focus_en: "necrotic recycling report", angle_zh: "尸体第一次被完整写入产出逻辑，而不再只是损失。", angle_en: "Bodies are being written into output logic instead of being treated as pure loss.", result_zh: "黑暗经济正式闭环。", result_en: "The dark economy has formed a closed loop.", breaking: true },
    TechTopic { code: "symbiotic_hosts", technology: TechnologyId::SymbioticHosts, category: EventCategory::SocialMutation, focus_zh: "共生宿主前哨", focus_en: "symbiotic hosts outpost", angle_zh: "蛆虫阶段第一次明确指向下一层社会结构。", angle_en: "For the first time, the maggot stage is pointing clearly toward the next social structure.", result_zh: "黑暗链条不再只是资源链。", result_en: "The dark chain is no longer only a resource chain.", breaking: false },
    TechTopic { code: "biotechnology", technology: TechnologyId::Biotechnology, category: EventCategory::IndustrialProgress, focus_zh: "生物技术侧记", focus_en: "biotechnology side note", angle_zh: "有机材料第一次开始反向塑造工业布局。", angle_en: "Organic material is beginning to reshape the industrial layout from the inside out.", result_zh: "工厂与育池之间的界线越来越薄。", result_en: "The line between factory and nursery is thinning.", breaking: false },
    TechTopic { code: "genetic_engineering", technology: TechnologyId::GeneticEngineering, category: EventCategory::SocialMutation, focus_zh: "基因工程快讯", focus_en: "genetic engineering flash", angle_zh: "黑暗链条的后果开始被写成可设计、可调参的对象。", angle_en: "The consequences of the dark chain are being reframed as things that can be designed and tuned.", result_zh: "社会即将进入被技术重新定义的阶段。", result_en: "Society is approaching a stage where technology rewrites what it means to be social.", breaking: false },
    TechTopic { code: "advanced_chemistry", technology: TechnologyId::AdvancedChemistry, category: EventCategory::IndustrialProgress, focus_zh: "高级化学工况", focus_en: "advanced chemistry condition", angle_zh: "腐化副产物第一次被大规模转译成工业配方。", angle_en: "Corrupt byproducts are being translated into industrial recipes at scale for the first time.", result_zh: "黑暗与工业正在共享同一张配方表。", result_en: "Dark matter and industry are starting to share one recipe sheet.", breaking: false },
    TechTopic { code: "nanotechnology", technology: TechnologyId::Nanotechnology, category: EventCategory::IndustrialProgress, focus_zh: "纳米技术观察", focus_en: "nanotechnology watch", angle_zh: "黑暗链条产出的更细微结构第一次被视作可制造对象。", angle_en: "The finer structures produced by the dark chain are being treated as manufacturable objects for the first time.", result_zh: "腐化开始进入微观工业。", result_en: "Corruption is entering microscopic industry.", breaking: false },
    TechTopic { code: "advanced_nanotech", technology: TechnologyId::AdvancedNanotech, category: EventCategory::IndustrialProgress, focus_zh: "高级纳米技术通报", focus_en: "advanced nanotech advisory", angle_zh: "分子级调参让黑暗副产物第一次被写成高精度材料来源。", angle_en: "Molecular-scale tuning is turning dark byproducts into a high-precision material source for the first time.", result_zh: "黑暗链条开始与尖端制造重叠。", result_en: "The dark chain is beginning to overlap with frontier manufacturing.", breaking: true },
    TechTopic { code: "renewable_energy", technology: TechnologyId::RenewableEnergy, category: EventCategory::IndustrialProgress, focus_zh: "可再生能源支线", focus_en: "renewable energy dispatch", angle_zh: "更稳的能源底盘让黑暗处理设施第一次拥有持续运行的可能。", angle_en: "A steadier energy base is giving dark treatment facilities sustained uptime for the first time.", result_zh: "暗链效率开始脱离偶然窗口。", result_en: "Dark-chain efficiency is detaching from lucky windows.", breaking: false },
    TechTopic { code: "advanced_robotics", technology: TechnologyId::AdvancedRobotics, category: EventCategory::IndustrialProgress, focus_zh: "高级机器人清污线", focus_en: "advanced robotics cleanup line", angle_zh: "高危清理作业第一次可以更多交给非人单元承担。", angle_en: "Hazard cleanup is being transferred to non-human units at scale for the first time.", result_zh: "黑暗链条正在重写“谁来承担风险”。", result_en: "The dark chain is rewriting who bears risk.", breaking: false },
    TechTopic { code: "symbiotic_hosts_followup", technology: TechnologyId::SymbioticHosts, category: EventCategory::SocialMutation, focus_zh: "宿主体系跟踪", focus_en: "host system follow-up", angle_zh: "宿主机制开始从技术设定转向可管理、可扩大的社会结构。", angle_en: "The host mechanism is shifting from a technical setup into a scalable social structure.", result_zh: "黑暗技术第一次真正踏进人口治理。", result_en: "Dark technology has truly entered population governance.", breaking: true },
    TechTopic { code: "electronics_dark", technology: TechnologyId::Electronics, category: EventCategory::IndustrialProgress, focus_zh: "暗链电子防护栏", focus_en: "dark-chain electronics shield", angle_zh: "电子监控和传感阵列开始第一次全面覆盖腐化处理区。", angle_en: "Electronic monitoring and sensor grids are beginning to cover the corrupted processing zone end to end for the first time.", result_zh: "黑暗链条第一次被高精度工业设备持续注视。", result_en: "The dark chain is under continuous watch by high-precision industry for the first time.", breaking: false },
];

const HYBRID_TECH_TOPICS: [TechTopic; 12] = [
    TechTopic {
        code: "hive_mind",
        technology: TechnologyId::HiveMindProtocol,
        category: EventCategory::SocialMutation,
        focus_zh: "蜂巢协议评论",
        focus_en: "hive mind protocol commentary",
        angle_zh: "共生社会第一次拥有了真正意义上的共享协调协议。",
        angle_en: "The symbiotic society now has a real shared coordination protocol.",
        result_zh: "个体与群体的界线进一步模糊。",
        result_en: "The boundary between individual and collective is blurring further.",
        breaking: true,
    },
    TechTopic {
        code: "mass_production",
        technology: TechnologyId::MassProduction,
        category: EventCategory::IndustrialProgress,
        focus_zh: "大规模生产特写",
        focus_en: "mass production feature",
        angle_zh: "混合劳动力第一次和大规模生产逻辑接通。",
        angle_en: "Hybrid labor is being connected to mass-production logic for the first time.",
        result_zh: "共生阶段开始拥有真正的文明级扩张能力。",
        result_en: "The symbiotic stage is acquiring civilization-scale expansion capacity.",
        breaking: false,
    },
    TechTopic {
        code: "robotics",
        technology: TechnologyId::Robotics,
        category: EventCategory::IndustrialProgress,
        focus_zh: "机器人岗位整编",
        focus_en: "robotic station reorganization",
        angle_zh: "自动工位正被塞进人类与混合人口之间的缝隙。",
        angle_en:
            "Automated stations are being wedged into the gaps between human and hybrid labor.",
        result_zh: "劳动力结构因此更像网络，而不是名单。",
        result_en: "Labor structure is starting to look more like a network than a roster.",
        breaking: false,
    },
    TechTopic {
        code: "advanced_ai",
        technology: TechnologyId::AdvancedAI,
        category: EventCategory::EndgameSign,
        focus_zh: "高级人工智能侧栏",
        focus_en: "advanced AI sidebar",
        angle_zh: "判断与调度正在悄悄从人工与共生意志之间脱离出去。",
        angle_en: "Judgment and dispatch are quietly detaching from both human and symbiotic will.",
        result_zh: "决策即将拥有第三种主体。",
        result_en: "Decision-making is on the verge of gaining a third actor.",
        breaking: false,
    },
    TechTopic {
        code: "renewable_energy",
        technology: TechnologyId::RenewableEnergy,
        category: EventCategory::IndustrialProgress,
        focus_zh: "可再生能源专讯",
        focus_en: "renewable energy dispatch",
        angle_zh: "更稳定的能源地基让混合社会第一次看到长周期秩序。",
        angle_en:
            "A steadier energy base is giving hybrid society its first glimpse of long-cycle order.",
        result_zh: "稳定不再只是理想状态。",
        result_en: "Stability is no longer only an aspiration.",
        breaking: false,
    },
    TechTopic {
        code: "nuclear_energy",
        technology: TechnologyId::NuclearEnergy,
        category: EventCategory::EndgameSign,
        focus_zh: "核能风险简报",
        focus_en: "nuclear risk brief",
        angle_zh: "更高能级的供给方案第一次被摆上共生社会的桌面。",
        angle_en:
            "Higher-energy supply plans have reached the hybrid society's table for the first time.",
        result_zh: "风险管理将因此变成文明级议题。",
        result_en: "Risk management is becoming a civilizational question now.",
        breaking: true,
    },
    TechTopic {
        code: "computer_technology_hybrid",
        technology: TechnologyId::ComputerTechnology,
        category: EventCategory::IndustrialProgress,
        focus_zh: "混合社会算力中枢",
        focus_en: "hybrid compute nexus",
        angle_zh: "计算系统开始把人类、混合人口与自动工位纳入同一张预测图。",
        angle_en: "Computing systems are beginning to place humans, hybrids, and automated stations inside one prediction map.",
        result_zh: "混合社会第一次拥有真正统一的运营视角。",
        result_en: "Hybrid society is acquiring a genuinely unified operational view.",
        breaking: false,
    },
    TechTopic {
        code: "ai_technology_hybrid",
        technology: TechnologyId::AITechnology,
        category: EventCategory::SocialMutation,
        focus_zh: "共生 AI 旁听席",
        focus_en: "symbiotic AI observer seat",
        angle_zh: "算法开始参与共生秩序的解释工作，而不仅是调度工作。",
        angle_en: "Algorithms are beginning to interpret symbiotic order, not merely dispatch it.",
        result_zh: "社会协调第一次拥有机器旁白。",
        result_en: "Social coordination now has a machine narrator for the first time.",
        breaking: false,
    },
    TechTopic {
        code: "advanced_robotics_hybrid",
        technology: TechnologyId::AdvancedRobotics,
        category: EventCategory::IndustrialProgress,
        focus_zh: "高级机器人协作岗",
        focus_en: "advanced robotics collaboration desk",
        angle_zh: "高阶机器人正在把高风险工位从对抗关系改写成协作关系。",
        angle_en: "Advanced robotics is rewriting high-risk stations from adversarial contact into coordinated cooperation.",
        result_zh: "混合岗位的分工线因此再次移动。",
        result_en: "The line of division inside hybrid labor is moving again.",
        breaking: false,
    },
    TechTopic {
        code: "biotechnology_hybrid",
        technology: TechnologyId::Biotechnology,
        category: EventCategory::SocialMutation,
        focus_zh: "生物技术共生档案",
        focus_en: "biotech symbiosis archive",
        angle_zh: "生物技术开始把共生体从偶发结果写成可持续维护对象。",
        angle_en: "Biotechnology is turning the symbiotic body from an accidental outcome into a maintainable system.",
        result_zh: "共生社会开始拥有真正的长期保养逻辑。",
        result_en: "Symbiotic society is gaining a genuine long-term maintenance logic.",
        breaking: false,
    },
    TechTopic {
        code: "genetic_engineering_hybrid",
        technology: TechnologyId::GeneticEngineering,
        category: EventCategory::SocialMutation,
        focus_zh: "混合谱系修订案",
        focus_en: "hybrid lineage revision",
        angle_zh: "基因层面的可调节性第一次进入公共制度想象。",
        angle_en: "Genetic tunability has entered public institutional imagination for the first time.",
        result_zh: "身份、身体与制度开始被一起重写。",
        result_en: "Identity, body, and institution are beginning to be rewritten together.",
        breaking: true,
    },
    TechTopic {
        code: "advanced_nanotech_hybrid",
        technology: TechnologyId::AdvancedNanotech,
        category: EventCategory::EndgameSign,
        focus_zh: "高级纳米共构简报",
        focus_en: "advanced nanotech co-assembly brief",
        angle_zh: "纳米级制造开始直接参与混合体修复与工业构件生成。",
        angle_en: "Nanoscale fabrication is directly entering hybrid-body repair and industrial component generation.",
        result_zh: "社会与工厂的边界被进一步压平。",
        result_en: "The boundary between society and factory is flattening further.",
        breaking: true,
    },
];

const COLLECTIVE_TECH_TOPICS: [TechTopic; 12] = [
    TechTopic {
        code: "collective_awakening",
        technology: TechnologyId::CollectiveAwakening,
        category: EventCategory::EndgameSign,
        focus_zh: "集体觉醒简报",
        focus_en: "collective awakening brief",
        angle_zh: "共享意识从隐喻正式转向运行中的主系统。",
        angle_en: "Shared consciousness is moving from metaphor into active system status.",
        result_zh: "终局阶段的主语已经发生变化。",
        result_en: "The subject of the endgame has changed.",
        breaking: true,
    },
    TechTopic {
        code: "quantum_computing",
        technology: TechnologyId::QuantumComputing,
        category: EventCategory::IndustrialProgress,
        focus_zh: "量子计算头条",
        focus_en: "quantum computing headline",
        angle_zh: "算力开始直接改写资源网络的结构。",
        angle_en: "Compute power is directly rewriting the shape of the resource network.",
        result_zh: "推演能力本身已成为产能的一部分。",
        result_en: "Forecasting itself has become part of production.",
        breaking: false,
    },
    TechTopic {
        code: "space_exploration",
        technology: TechnologyId::SpaceExploration,
        category: EventCategory::EndgameSign,
        focus_zh: "太空探索特刊",
        focus_en: "space exploration special",
        angle_zh: "远征第一次从象征目标变成排产任务。",
        angle_en: "Expedition has crossed from symbolic goal into production schedule.",
        result_zh: "文明的边界被正式推向外层。",
        result_en: "The frontier of civilization is being pushed outward in formal terms.",
        breaking: false,
    },
    TechTopic {
        code: "time_manipulation",
        technology: TechnologyId::TimeManipulation,
        category: EventCategory::EndgameSign,
        focus_zh: "时间操控专稿",
        focus_en: "time manipulation feature",
        angle_zh: "时间窗口开始被视作和资源窗口同样可调度的对象。",
        angle_en:
            "Time windows are being treated as schedulable objects alongside resource windows.",
        result_zh: "终局调度第一次不再只管理空间。",
        result_en: "Endgame dispatch is no longer managing space alone.",
        breaking: true,
    },
    TechTopic {
        code: "consciousness_upload",
        technology: TechnologyId::ConsciousnessUpload,
        category: EventCategory::EndgameSign,
        focus_zh: "意识上传纪要",
        focus_en: "consciousness upload memorandum",
        angle_zh: "身体与身份开始被拆成两个可分开处理的环节。",
        angle_en: "Body and identity are beginning to separate into distinct administrable layers.",
        result_zh: "社会将不得不重新定义生存本身。",
        result_en: "Society will be forced to redefine survival itself.",
        breaking: true,
    },
    TechTopic {
        code: "antimatter_energy",
        technology: TechnologyId::AntimatterEnergy,
        category: EventCategory::EndgameSign,
        focus_zh: "反物质能源通报",
        focus_en: "antimatter energy advisory",
        angle_zh: "极端能级被正式写入文明级供给逻辑。",
        angle_en: "Extreme energy levels are being written into civilization-scale supply logic.",
        result_zh: "从这里开始，每一次事故都可能改写整张图。",
        result_en: "From here onward, each accident can redraw the entire map.",
        breaking: true,
    },
    TechTopic {
        code: "fusion_energy",
        technology: TechnologyId::FusionEnergy,
        category: EventCategory::EndgameSign,
        focus_zh: "聚变能源主稿",
        focus_en: "fusion energy lead",
        angle_zh: "终局供能第一次拥有了足以支撑文明级连续运转的热核底盘。",
        angle_en: "Endgame power now has a thermonuclear base capable of sustaining civilization-scale continuity.",
        result_zh: "能源问题开始从瓶颈变成扩张杠杆。",
        result_en: "Energy is shifting from bottleneck into expansion leverage.",
        breaking: true,
    },
    TechTopic {
        code: "terraforming",
        technology: TechnologyId::Terraforming,
        category: EventCategory::EndgameSign,
        focus_zh: "地球化改造长文",
        focus_en: "terraforming longform",
        angle_zh: "聚落第一次公开讨论如何把外部环境改造成适配自身的生态外壳。",
        angle_en: "The settlement is publicly discussing how to remake external environments into shells suited to itself.",
        result_zh: "文明第一次不再只适应世界，而是准备重写世界。",
        result_en: "Civilization is preparing not merely to survive the world but to rewrite it.",
        breaking: false,
    },
    TechTopic {
        code: "dimensional_travel",
        technology: TechnologyId::DimensionalTravel,
        category: EventCategory::EndgameSign,
        focus_zh: "维度旅行纪要",
        focus_en: "dimensional travel memorandum",
        angle_zh: "外向扩张第一次超出轨道与地表，触及更陌生的空间层。",
        angle_en: "Outbound expansion is moving beyond orbit and surface into stranger spatial layers.",
        result_zh: "终局地图将不再只用距离衡量。",
        result_en: "The endgame map will no longer be measured by distance alone.",
        breaking: true,
    },
    TechTopic {
        code: "immortality",
        technology: TechnologyId::Immortality,
        category: EventCategory::SocialMutation,
        focus_zh: "永生技术争鸣",
        focus_en: "immortality technology debate",
        angle_zh: "存续不再只是医疗议题，而被抬升为制度与身份议题。",
        angle_en: "Continuation is no longer merely medical; it has become an institutional and identity question.",
        result_zh: "寿命边界开始退出旧社会语法。",
        result_en: "The boundary of lifespan is exiting the grammar of the old society.",
        breaking: true,
    },
    TechTopic {
        code: "godhood",
        technology: TechnologyId::Godhood,
        category: EventCategory::EndgameSign,
        focus_zh: "神级技术社论",
        focus_en: "godhood editorial",
        angle_zh: "终局技术第一次让“治理”与“造物”之间的区别变得不再稳定。",
        angle_en: "Endgame technology is destabilizing the line between governance and creation itself.",
        result_zh: "文明将被迫重新命名自己的高度。",
        result_en: "Civilization will be forced to rename its own altitude.",
        breaking: true,
    },
    TechTopic {
        code: "omniscience",
        technology: TechnologyId::Omniscience,
        category: EventCategory::EndgameSign,
        focus_zh: "全知系统快报",
        focus_en: "omniscience system flash",
        angle_zh: "当所有链路被持续收束到一个感知平面，信息本身开始拥有支配性重量。",
        angle_en: "As all lines are folded into one sensing plane, information itself acquires ruling weight.",
        result_zh: "终局不只是产能终局，也是一场认知终局。",
        result_en: "The endgame is not only a production endgame but a cognitive one.",
        breaking: true,
    },
];

pub(super) fn stage_subjects(stage: GameStage) -> &'static [StageSubject] {
    match stage {
        GameStage::Genesis => &GENESIS_STAGE_SUBJECTS,
        GameStage::Workers => &WORKERS_STAGE_SUBJECTS,
        GameStage::Maggot => &MAGGOT_STAGE_SUBJECTS,
        GameStage::Hybrid => &HYBRID_STAGE_SUBJECTS,
        GameStage::Collective => &COLLECTIVE_STAGE_SUBJECTS,
    }
}

pub(super) fn tech_topics(stage: GameStage) -> &'static [TechTopic] {
    match stage {
        GameStage::Genesis => &GENESIS_TECH_TOPICS,
        GameStage::Workers => &WORKERS_TECH_TOPICS,
        GameStage::Maggot => &MAGGOT_TECH_TOPICS,
        GameStage::Hybrid => &HYBRID_TECH_TOPICS,
        GameStage::Collective => &COLLECTIVE_TECH_TOPICS,
    }
}

pub(super) fn template_capacity() -> usize {
    EVENT_TEMPLATE_CAPACITY
}

pub(super) fn catalog_capacity() -> usize {
    template_capacity() * REPORT_VARIANT_COUNT
}

pub(super) fn trait_voice_pack_zh(
    trait_value: Trait,
) -> (
    &'static [&'static str],
    &'static [&'static str],
    &'static [&'static str],
) {
    match trait_value {
        Trait::Diligent
        | Trait::Hardworking
        | Trait::Efficient
        | Trait::Persevering
        | Trait::Careful => (
            &[
                "先把岗位守住",
                "越是这时候越不能乱",
                "流程还在转就有机会",
                "把这轮先顶过去",
                "别让今天白白损失掉",
                "先把关键工位稳住",
                "这时候最怕有人先松手",
                "班组不能在这个节骨眼散掉",
                "先把今天的损失压到最低",
                "再难也得把工序接住",
            ],
            &[
                "大家至少还知道自己该做什么",
                "真正危险的是节拍断掉",
                "我宁愿多值一轮班，也不想看系统停住",
                "现在需要更稳的安排",
                "岗位比口号更诚实",
                "只要流程没断，局面就还有补救空间",
                "大家最需要的是能落地的调度，不是空话",
                "机器和人都怕犹豫，稳比快更重要",
                "先让班组知道下一步做什么，情绪就不会先崩",
                "现在每一分钟都该拿来保住产线",
            ],
            &[
                "别松手。",
                "先把这轮扛住。",
                "能修就修。",
                "数字会骗人，工位不会。",
                "现在最重要的是稳住。",
                "先别让产线掉下来。",
                "该顶的时候就得顶。",
                "把活接住再说。",
                "稳住就还有明天。",
                "先把口子堵上。",
                "别让流程断气。",
                "先顶住这一班。",
                "守住比漂亮更重要。",
                "先让线活着。",
                "乱不得。",
            ],
        ),
        Trait::Lazy
        | Trait::Slow
        | Trait::SlowLearner
        | Trait::Clumsy
        | Trait::Careless
        | Trait::Forgetful => (
            &[
                "听起来又要加班",
                "他们总说只是临时问题",
                "我只想知道今晚会不会更难熬",
                "消息倒是比饭来得快",
                "最好别再临时改流程了",
                "每次出事都先轮到我们加班",
                "我就知道这事不会轻易过去",
                "现在连喘口气都像奢侈",
                "最麻烦的总是落到值班的人头上",
                "又来一轮临时调整是吧",
            ],
            &[
                "每次都说可控，结果总会多一堆表格",
                "如果不是落到我头上，我可能都不想注意",
                "别把所有麻烦都往班组里塞",
                "我希望别再把事情搞复杂",
                "这事听起来已经够麻烦了",
                "上头一句协调，下面就得多跑几圈",
                "我只求别把简单问题做成长期折磨",
                "能不能先把吃饭和休息保证了再谈别的",
                "每次都要我们自己想办法消化后果",
                "如果流程再改一次，肯定又有人跟不上",
            ],
            &[
                "能早点结束就好。",
                "别再拖长了。",
                "希望这次不是长期安排。",
                "我可不想赔上一整夜。",
                "拜托简单一点。",
                "让我先把这班混过去。",
                "今天最好别再加码。",
                "麻烦别变成常态。",
                "我只想准点下班。",
                "别再往下压了。",
                "别让我再多背一层锅。",
                "今天到此为止行吗。",
                "别再来新花样。",
                "先让我喘口气。",
                "这事最好别升级。",
            ],
        ),
        Trait::Intelligent | Trait::FastLearner | Trait::Genius | Trait::Creative => (
            &[
                "这件事的因果链其实很清楚",
                "从系统角度看",
                "我怀疑这只是更大模式的一部分",
                "如果把变量摊开看",
                "这里面一定有可重复的结构",
                "我更愿意把它视为一个可分析的样本",
                "先别急着把它叫做事故",
                "这个节点出现得太有规律了",
                "从逻辑链上看它并不突然",
                "如果把前后读数放一起看",
            ],
            &[
                "现象本身比通报更重要",
                "他们说的是结果，不是机制",
                "真正关键的是它为何在这个时点出现",
                "只要样本够多，这就不再神秘",
                "我更关心它会怎么改写后续生产逻辑",
                "真正值得记录的是系统为何允许它发生",
                "每次异常都在透露主线的薄弱处",
                "只看表面波动会错过核心因子",
                "这不是孤例，而是某种阈值被碰到了",
                "如果模型成立，下一次波动会来得更快",
            ],
            &[
                "这不是噪音，是结构。",
                "我想看原始记录。",
                "迟早有人会把它建模出来。",
                "这里面藏着下一步的钥匙。",
                "现在缺的是诚实数据。",
                "先把因果链画出来。",
                "别让情绪盖过样本。",
                "结构比口号更重要。",
                "它迟早会暴露规律。",
                "关键变量已经浮出来了。",
                "先别浪费这个样本。",
                "模式已经在说话了。",
                "这行数据很贵。",
                "别急着下结论，先画图。",
                "真正的答案在序列里。",
            ],
        ),
        Trait::Social | Trait::Charismatic | Trait::Optimistic => (
            &[
                "大家今天都在讨论这件事",
                "这个消息一出，工棚就有反应",
                "我敢说每个班组都听到了风声",
                "你能从表情上看出来",
                "人群的情绪变得很快",
                "连平时不吭声的人都开始交换消息了",
                "走廊里的话题几分钟就换成了这个",
                "这事一出来，大家看彼此的眼神都不一样了",
                "消息传得比广播还快",
                "连食堂里都在说这件事",
            ],
            &[
                "恐慌会传得比通知更快，但希望也一样",
                "只要把话讲明白，队伍就不会散",
                "比起沉默，我宁愿大家把担心说出来",
                "现在最需要的是能听懂的解释",
                "只要节拍没全乱，局面就还能接住",
                "大家最怕的是没人出来把话说明白",
                "如果有人肯承担解释责任，情绪就不会继续下坠",
                "传言会自己生长，所以回应必须更快",
                "我们需要的是把同一件事讲成同一个版本",
                "队伍不会因为坏消息散，只会因为沉默散",
            ],
            &[
                "现在还不是最糟的时候。",
                "总会有人把事情接住。",
                "别先把彼此吓坏。",
                "我们至少还在同一条线上。",
                "如果要变，也要一起变。",
                "先别把希望说没了。",
                "能说清楚就还有余地。",
                "人心别先散。",
                "先让大家知道自己不是孤立的。",
                "坏消息也得有人稳着讲。",
                "别让传言赢了。",
                "先把话讲明白。",
                "人还在，就能接。",
                "把情绪拢住再说。",
                "别让队伍先碎。",
            ],
        ),
        Trait::Loner | Trait::Shy => (
            &[
                "我平时不太参与这种讨论",
                "如果一定要问",
                "我更习惯先记下来",
                "我不想太早下结论",
                "你可以把这当成个人观察",
                "我宁愿多看两轮再开口",
                "先别把我的名字写得太显眼",
                "我通常只在被问到时才说",
                "我不确定这是不是适合公开说的话",
                "如果一定要记录，就按事实写",
            ],
            &[
                "大家说得太多时，重要细节反而会被盖住",
                "有些变化在安静的时候更明显",
                "不出声不代表没看见",
                "我不觉得现在有人完全理解它",
                "再观察一轮会更稳妥",
                "很多东西不是没发生，只是被更响的声音压过去了",
                "我更相信反复出现的细节，而不是第一波解读",
                "真相通常不会出现在最热闹的地方",
                "只要再看一班，很多人现在的说法就会自己失效",
                "先把记录留下，比急着表态更有用",
            ],
            &[
                "先别把话说满。",
                "噪音太大了。",
                "真实通常藏在安静处。",
                "还没到能下定论的时候。",
                "现在最缺的是清醒。",
                "再安静一点就能看出来了。",
                "别急着站队。",
                "让我再看一轮。",
                "沉默里信息更多。",
                "现在说死太早了。",
                "别让热闹替代判断。",
                "先把细节留下。",
                "现在最怕误读。",
                "再等一轮更稳。",
                "安静一点才听得见真相。",
            ],
        ),
        Trait::NightOwl | Trait::EarlyBird => (
            &[
                "这种波动总挑时段说话",
                "白班和夜班看到的像两套世界",
                "换班边缘最能看出问题",
                "我比很多人更早注意到节拍变化",
                "时段本身就是问题的一部分",
                "这类事总在最不该出波动的时候出波动",
                "晨班和夜班看到的不是同一张图",
                "时间窗一错开，很多问题立刻就暴露了",
                "我盯的不是新闻，是它出现的时刻",
                "时段比表面现象更诚实",
            ],
            &[
                "如果只看一个班次，结论肯定会偏",
                "真正的拐点总发生在大家最疲惫或最松弛的时候",
                "他们应该按时间窗来布置应对",
                "节拍一乱，时间感先出问题",
                "时钟往往比报告更诚实",
                "同一条产线在不同班次里会说不同的话",
                "想抓住规律，就得先抓住它出现的时间段",
                "很多错误不是突然发生，而是在换班缝隙里堆出来的",
                "时间分布本身就是线索，不是背景",
                "值班安排要是错了，再好的口径也会露底",
            ],
            &[
                "换个班次看会更清楚。",
                "这事有明确的时间纹理。",
                "再看一轮时间窗。",
                "信号不会随机出现。",
                "它有自己的时序。",
                "别忽略换班线。",
                "看钟表比看脸色更准。",
                "它总在特定时段露头。",
                "再追一轮时序。",
                "节拍本身会说话。",
                "看时间，别只看表情。",
                "它有固定出场顺序。",
                "再等下个时段。",
                "换班缝最会漏真相。",
                "先盯时间轴。",
            ],
        ),
    }
}

pub(super) fn trait_voice_pack_en(
    trait_value: Trait,
) -> (
    &'static [&'static str],
    &'static [&'static str],
    &'static [&'static str],
) {
    match trait_value {
        Trait::Diligent
        | Trait::Hardworking
        | Trait::Efficient
        | Trait::Persevering
        | Trait::Careful => (
            &[
                "Hold the station first",
                "This is exactly when people cannot scatter",
                "If the process still moves, there is still a chance",
                "Get through this cycle first",
                "Do not waste today",
                "Lock the critical stations down first",
                "This is where letting go becomes expensive",
                "The crew cannot come apart on a turn like this",
                "Keep today's losses contained first",
                "Whatever happens, the line still has to be caught",
            ],
            &[
                "At least the crews still know their jobs",
                "The real danger is losing the rhythm",
                "I would rather take another shift than watch the system stop",
                "What we need now is steadier planning",
                "The station is more honest than the slogan",
                "If the process remains intact, recovery is still possible",
                "People need actionable dispatch, not ceremonial language",
                "Machines and crews both punish hesitation",
                "Give the floor a next step and panic does not get the first move",
                "Every spare minute now should go into keeping the line alive",
            ],
            &[
                "Do not let go.",
                "Hold this round together.",
                "Fix what can still be fixed.",
                "The numbers can lie, the station usually does not.",
                "Stability matters most right now.",
                "Do not let the line drop.",
                "If it is time to hold, then hold.",
                "Catch the work first.",
                "If we stay steady, there is still a tomorrow.",
                "Close the breach first.",
                "Do not let the process lose its breath.",
                "Hold this shift first.",
                "Steady beats elegant right now.",
                "Keep the line alive.",
                "This is no time to shake loose.",
            ],
        ),
        Trait::Lazy
        | Trait::Slow
        | Trait::SlowLearner
        | Trait::Clumsy
        | Trait::Careless
        | Trait::Forgetful => (
            &[
                "Sounds like overtime again",
                "They always call it temporary",
                "I mostly want to know if tonight gets harder",
                "News arrives faster than food",
                "Please do not rewrite the process again",
                "Every incident somehow becomes our overtime",
                "I knew this was never going away quietly",
                "Even catching one breath feels expensive right now",
                "The ugliest jobs always land on whoever is on shift",
                "So this is another emergency adjustment, huh",
            ],
            &[
                "Every report says controllable and then another stack of forms shows up",
                "If it did not land on my shift, I might ignore it",
                "Do not dump every mess on the floor",
                "I really hope nobody makes this even more complicated",
                "This already sounds exhausting",
                "One sentence upstairs means three extra loops downstairs",
                "I just do not want a simple problem turned into a permanent burden",
                "Maybe guarantee food and sleep before adding another slogan",
                "It always ends with crews absorbing the consequence themselves",
                "If the process changes one more time, someone is definitely missing the handoff",
            ],
            &[
                "I hope this ends quickly.",
                "Do not drag it out.",
                "Please do not make it permanent.",
                "I am not losing a whole night to this.",
                "Keep it simple.",
                "Let me survive this shift first.",
                "Do not pile more on today.",
                "Do not let inconvenience become policy.",
                "I would like to leave on time once.",
                "Please stop pushing downward.",
                "Do not hand me another layer of blame.",
                "Can today just stop here.",
                "Please no new tricks tonight.",
                "Let me breathe first.",
                "This does not need to escalate.",
            ],
        ),
        Trait::Intelligent | Trait::FastLearner | Trait::Genius | Trait::Creative => (
            &[
                "The causal chain is actually visible",
                "From a system perspective",
                "I suspect this is only one face of a larger pattern",
                "If you spread the variables out",
                "There has to be a repeatable structure underneath this",
                "I would rather treat this as an analyzable sample",
                "Do not call it an accident too quickly",
                "This node is appearing with suspicious regularity",
                "Across the chain, this is not as sudden as it looks",
                "Put the before-and-after readings side by side",
            ],
            &[
                "The phenomenon matters more than the official line",
                "They are describing outcomes rather than mechanisms",
                "The real question is why it surfaced now",
                "Once the sample gets larger, this stops looking mystical",
                "I care more about how it rewrites downstream logic",
                "What matters is why the system allowed it to happen",
                "Each anomaly is exposing a weak segment of the main loop",
                "Watching the surface wave alone misses the core factor",
                "This is not a one-off, it is a threshold being touched",
                "If the model is right, the next swing comes sooner",
            ],
            &[
                "This is structure, not noise.",
                "I want the raw log.",
                "Someone will model this sooner or later.",
                "There is a key hidden inside this.",
                "What we lack is honest data.",
                "Map the causal chain first.",
                "Do not let mood outrun the sample.",
                "Structure matters more than rhetoric.",
                "The pattern will expose itself again.",
                "The key variables are already visible.",
                "Do not waste this sample.",
                "The pattern is already speaking.",
                "This line of data is expensive.",
                "Plot first, argue later.",
                "The answer is in the sequence.",
            ],
        ),
        Trait::Social | Trait::Charismatic | Trait::Optimistic => (
            &[
                "Everybody is talking about this today",
                "The moment the bulletin landed, the room reacted",
                "Every crew heard the rumor",
                "You could read it on people's faces",
                "The mood shifted immediately",
                "Even the quiet ones started trading updates",
                "The hallway changed topics in minutes",
                "The way people looked at each other changed with the bulletin",
                "The rumor outran the speaker system",
                "Even the canteen is talking about it now",
            ],
            &[
                "Panic travels faster than policy, but hope does too",
                "If someone explains it plainly, the team will hold",
                "I would rather hear fear out loud than watch it ferment in silence",
                "People need language they can actually trust",
                "As long as the rhythm does not fully break, the floor will not either",
                "People fear silence more than bad news",
                "If someone owns the explanation, the mood stops falling quite so fast",
                "Rumor grows on its own, so response has to move faster",
                "We need one shared version of the same event",
                "Crews do not scatter because of truth, they scatter because no one speaks clearly",
            ],
            &[
                "This is not the worst point yet.",
                "Somebody always catches the fall.",
                "We do not need to scare each other into collapse.",
                "At least we are still on one line.",
                "If change is coming, we face it together.",
                "Do not bury hope before the facts do.",
                "If we can explain it, we still have room.",
                "Do not let morale scatter first.",
                "People need to know they are not alone in the room.",
                "Even bad news can be carried steadily.",
                "Do not let rumor win.",
                "Explain it before fear does.",
                "If people remain, the line remains.",
                "Gather the mood first.",
                "Do not let the crew break before the system does.",
            ],
        ),
        Trait::Loner | Trait::Shy => (
            &[
                "I do not usually take part in these discussions",
                "If you really need a quote",
                "I prefer to write things down first",
                "I do not want to conclude too early",
                "Take this as a private observation",
                "I would rather watch two more cycles first",
                "Please do not put my name in large type",
                "I usually speak only when asked directly",
                "I am not sure this belongs in the open yet",
                "If you record it, record the fact and not the noise",
            ],
            &[
                "When everyone gets loud, the key details disappear first",
                "Some changes are easier to see in silence",
                "Not speaking does not mean not noticing",
                "I do not think anyone fully understands it yet",
                "Watching one more cycle would be safer",
                "Many things are not absent, only drowned out",
                "I trust repeated details more than first explanations",
                "Truth rarely sits in the loudest corner",
                "Give it one more shift and half the current talking points will collapse",
                "A careful record is worth more than a fast position",
            ],
            &[
                "Do not rush the conclusion.",
                "There is too much noise.",
                "Truth usually hides in the quiet parts.",
                "It is too early for certainty.",
                "Clarity is what is missing right now.",
                "Give it more quiet.",
                "Do not pick a side too early.",
                "Let me watch one more round.",
                "Silence is carrying more information.",
                "It is too soon to lock the story down.",
                "Do not let heat replace judgment.",
                "Keep the details first.",
                "Misreading is the real risk right now.",
                "One more cycle will tell more.",
                "Quiet is where the truth is still audible.",
            ],
        ),
        Trait::NightOwl | Trait::EarlyBird => (
            &[
                "This kind of swing always speaks through timing",
                "Day crews and night crews are seeing different worlds",
                "Shift edges reveal the problem fastest",
                "I noticed the rhythm change before most people did",
                "Time windows are part of the issue itself",
                "These swings always arrive at the worst possible hour",
                "Morning crews and night crews are not reading the same picture",
                "The timing gap exposes more than the headline does",
                "I track when it arrives, not just what it is called",
                "Time tells the truth before policy does",
            ],
            &[
                "Any conclusion built on one shift alone will be biased",
                "The turning point always arrives when people are either tired or loose",
                "Response plans should be organized around time windows",
                "Once rhythm breaks, time is the first casualty",
                "The clock is often more honest than the report",
                "One line speaks differently depending on which shift is watching it",
                "To catch the pattern, first catch the hour it prefers",
                "A lot of failures are assembled inside handoff seams",
                "Time distribution is evidence, not scenery",
                "If scheduling is wrong, even perfect messaging starts leaking",
            ],
            &[
                "Look at another shift and it gets clearer.",
                "This has a visible time texture.",
                "Watch one more time window.",
                "Signals do not arrive at random.",
                "It has its own sequence.",
                "Do not ignore the handoff line.",
                "The clock reads truer than the faces do.",
                "It always shows up in a favored slot.",
                "Track one more sequence.",
                "Rhythm speaks for itself.",
                "Watch the clock, not just the faces.",
                "It enters in fixed order.",
                "Wait for the next window.",
                "Handoffs leak truth first.",
                "Start with the timeline.",
            ],
        ),
    }
}
